### ISSUE TITLE
Allow nested forms

### ISSUE THREAD

**Issue by Aleksion** [msaraiva/surface#100]
It seems like Fields and Inputs further down the chain uses the **first** form context that's been defined, rather than the one that's closest in the hierarchy. Is it possible to either make it take the closest or provide a way to "target" a specific form context? Right now Fields' association to a form is implicit - it would be great to explicitly attach them to a form instance instead

**Comment by Aleksion** [comment]
Just fiddled around with this for over 2 hours. I tried changing the inner form to an explicit form_for and passing the form variable down to the inputs below it. The inputs were still sending their data up to the parent form..

I really love the Surface components and how logical they are. But figuring out what's happening here is a bit of a mystery

**Comment by msaraiva** [comment]
Hi @Aleksion!

We're currently replacing our translator with a new compiler and as soon it gets merged I'll start reviewing some of the existing features, including contexts. I'd love to see exactly what you're trying to achieve so maybe we'll be able to make it work. Can you provide some examples? 

Cheers.

**Comment by Aleksion** [comment]
Hi @msaraiva,


Originally I wanted to do a nested form so I could do change tracking on sub components (I needed to do some time conversion that I preferred to keep out of the main form). But I realized that it's a html limitation that's aggressively enforced by phoenix (only one form). I then decided to go for inputs_for so my iterated values (I'm doing opening hours where I run over a range for the week) can be grouped semantically together to make change tracking manageable. The real challenge with the surface components here, is that they don't allow for prop overrides of the form. So they'll pull the form instead of the inputs_for variable. 

So two things I can see being necessary:

- we need to tweak the form components so you can provide them with a form explicitly (pretty simple change that I did in my own checkbox component. I can commit that one so you can check it off the list)

- potentially consider how nested contexts behave. If you add an InputsFor below a Form I would expect it to pull the form from Above it and provide its own form to all the Fields and Inputs below it

It sounded like that isn't entirely trivial though?

**Comment by msaraiva** [comment]
@Aleksion I have already started working on a wrapper around `inputs_for` that addresses this issue. The reason I haven't push it yet is that it depends on this [new feature](https://github.com/msaraiva/surface/issues/66) which will be added after we merge the new compiler. BTW, the new compiler is about to be merged so it won't take long until we have that working ;)
