### ISSUE TITLE
[Proposal] Better support for populating context assigns from props

### ISSUE THREAD

**Issue by lnr0626** [msaraiva/surface#108]
I have a calendar component that has multiple views, and am using the context to pass along common configuration. It would be nice to be able to do this without adding a whole bunch of `context_name: assigns.prop_name` in my `init_context/1` method. 

My initial thought was something like:
```
property some_prop, :string
...
context set value, :string, from_prop: :some_prop
```
We could also support `from_prop: true` as shorthand for pulling the value from the prop that's named the same as the context assign and adding `scope: :only_children`.

@msaraiva suggested an alternative approach of:
```
property some_prop, :string
...
context set value, :string, default: ^some_prop
```

**Comment by lnr0626** [comment]
I think the second approach is a bit more consistent with the other API elements we have. It also would easily be extended to adding default values for context assigns (instead of just always defaulting to `nil` as we do now), and better implies what sort of behavior would occur if that context assign was returned from `init_context/1`

**Comment by msaraiva** [comment]
@lnr0626 does this still makes sense with the new `<Context>` component?

**Comment by lnr0626** [comment]
Nope, we can go ahead and close this
