### ISSUE TITLE
Event Handling in Nested Live Components

### ISSUE THREAD

**Issue by coryc5** [msaraiva/surface#116]
If you nest a live component within another, and the parent live component passes an event to the child live component, should the event get handled by the parent's `handle_event/3` callback? or is the correct way to pass in a dom selector and set the `phx-target`?

Here is an example:

```elixir
defmodule ButtonLiveComponent do
  use Surface.LiveComponent

  property(click, :event, required: true)
  property(name, :string, required: true)

  def render(assigns) do
    ~H"""
    <button :on-phx-click={{ @click }}>{{@name}}</button>
    """
  end

  def handle_event(topic, _params, socket) do
    IO.inspect({__MODULE__, topic})

    {:noreply, socket}
  end
end

defmodule ParentButtonLiveComponent do
  use Surface.LiveComponent

  def render(assigns) do
    ~H"""
    <div>
      <ButtonLiveComponent click="PARENT_CLICK" name="Parent Button" id="CHILD" />
    </div>
    """
  end

  def handle_event(topic, _params, socket) do
    IO.inspect({__MODULE__, topic})

    {:noreply, socket}
  end
end

defmodule ExampleLiveView do
  use Surface.LiveView

  def render(assigns) do
    ~H"""
    <div>
      <div><ButtonLiveComponent click="REGULAR_CLICK" name="Regular Button" id="REGULAR_BUTTON" /></div>
      <div><ParentButtonLiveComponent id="PARENT" /></div>
    </div>
    """
  end

  def handle_event(topic, _params, socket) do
    IO.inspect({__MODULE__, topic})

    {:noreply, socket}
  end
end
```

Here, the "Parent Button" event gets handled in `ButtonLiveComponent` instead of `ParentButtonLiveComponent`.

**Comment by msaraiva** [comment]
Hi @coryc5!

By default, events are handled by the caller unless the `target` is explicitly specified. So the event `"PARENT_CLICK"` should be handled by `ParentButtonLiveComponent `. If not, it's a bug. Which version are you using? The one on `master`?

**Comment by coryc5** [comment]
@msaraiva i was using the latest on hex, but i just upgraded to master and things look good. i am now seeing `ParentButtonLiveComponent` handle the event, so this doesn't seem to be an issue

thanks!
