### ISSUE TITLE
LiveComponent-s use wrong namespace for handle_info

### ISSUE THREAD

**Issue by yoann9344** [msaraiva/surface#146]
When I omitted ` :on-phx-click` I had the error :
`function DemoWeb.TestLive.handle_event/3 is undefined or private`
Normal. But when solved it, I got an error on `handle_info` :
`function DemoWeb.TestLive.handle_info/2 is undefined or private`

I'm a last rain's newbie on elixir and phoenix, so maybe I'm totally wrong.
And for this reason, I have blindly tried few other cases : 
- add `phx-target="{{ @myself }}"`
- add an event property

_building.ex_
```elixir
defmodule Building do
  use Surface.LiveComponent
  alias Demo.Building
  alias Phoenix.PubSub

  property name, :string # , default: "Error"
  @topic Building.topic

  def mount(socket) do
    ...
  end

  def handle_event("upgrade", _, socket) do
    socket = socket 
             |> assign(:level, Building.level_up())
    {:noreply, socket}
  end

  def handle_info({:level, level}, socket) do
    {:noreply, assign(socket, level: level)}
  end
end
```
_building.sface_
```html
<div>
    <h1>{{ @name }} lvl {{ @level }}</h1>
  <h2>Coût :</h2>
  <Resources resources={{ @cost }}></Resources>
  <button :on-phx-click="upgrade">Upgrade</button>
</div>
```

_test_live.sface_
```html
<Building id="bakery1" name="bakery"></Building>
```

Ps : And it works when I use a `Surface.LiveView` instead of a `Surface.LiveComponent`, but I'm not able to receive the property (or data) name (which I receive even with the LiveComponent's error) :

_building.ex_
```elixir
defmodule Building do
  use Surface.LiveView
  alias Demo.Building
  alias Phoenix.PubSub
  
  data name, :string
  @topic Building.topic
  
  def mount(_params, _session, socket) do
    ...
  end

  def handle_event("upgrade", _, socket) do
    socket = socket 
             |> assign(:level, Building.level_up())
    {:noreply, socket}
  end

  def handle_info({:level, level}, socket) do
    {:noreply, assign(socket, level: level)}
  end
end
```

**Comment by msaraiva** [comment]
Hi @yoann9344!

Implementing `handle_info/2` on a `LiveComponent` has no effect as they are not `GenServer`s. You need to use a `LiveView` to receive PubSub messages.
