### ISSUE TITLE
Additional compile-time validation

### ISSUE THREAD

**Issue by msaraiva** [msaraiva/surface#151]
## Slots

Since using `<slot/>` is now mandatory, there are some nice extra compile-time checks we can perform now. Some examples:

### Unused slot props

```elixir
slot default, props: [:value, :max]
#                             ^^^^

def render(assigns) do
  ~H"""
  <div>
    <slot :props={{ value: @value }}/>
  </div>
  """
end
```

```
warning: slot prop :max is declared but never used.
```

### Unused slots

```elixir
slot header
slot body
#    ^^^^

def render(assigns) do
  ~H"""
  <div>
    <slot name="header"/>
  </div>
  """
end
```

```
warning: slot "body" is declared but never used.
```

### Renderless slots implementing `render/1`

```elixir
defmodule Footer do
 use Surface.Component, slot: "footer"

 def render(assigns) do
  ~H"""
    ...
  """
 end
end
```

```
warning: cannot implement render for renderless components.
```

### Required slot with fallback

```elixir
  slot default, required: true

  def render(assigns) do
    ~H"""
    <div>
      <slot>
        <div>
          Fallback content
        </div>
      </slot>
    </div>
    """
  end
```

```
warning: fallback content of required slots will never be used. Either make the slot optional or remove the fallback content. 
```

### Undefined context value

It would require us to create either a `fetch!` property or a modifier for `get` like `get.required={{...}}`. 

I believe this validation can only happen in the `__after_compile__` of a `Surface.LiveView`.

```elixir
def render(assigns) do
  ~H"""
  <Context put={{ lang: "Elxir" }}>
    ...
    <Context fetch!={{ langu: l }}>
      ...
    </Context>
  </Context>
  """
end
```

```
CompileError: no context value named :langu defined in any of the parent components.  
```

**Comment by margusp2heathmont** [comment]
Hello, Marlus! I hope you are doing good! :)

Old format of context properties supported (Surface built-in) types.

```
  context set theme, :any # or :string
```

New does not:

```
<Context set={{ :theme }}>
  {{ @theme.color }}
</Context>
```

Is it possible to get arbitrary type support for props, data and context? 

Code hinting and validation in IDE (not runtime) is a must for teams with more than 2 members.

**Comment by msaraiva** [comment]
Hi @margusp2heathmont!

> Is it possible to get arbitrary type support for props, data and context?

We can try to add support for types in the future, however, we'll not be able to do it like it was since we can now have multiple context values defined with the same name in the same component, in different places, like:

```
<Context set={{ item: a_string }}>
   <slot name="slot1"/>
</Context>
...
<Context set={{ item: an_integer }}>
   <slot name="slot2"/>
</Context>
```

So we need to set the type for each one of them.

> Code hinting and validation in IDE (not runtime) is a must for bigger teams

I agree and we'll try our best to bring some of that to Surface. Code hinting will be possible and it's already planned. Just be aware that we can certainly do some nice validations at compile-time but Elixir is still a dynamically typed language so there will still be many many cases where there will be nothing that we can do about it.

**Comment by msaraiva** [comment]
I'm closing this for now as there's no plans to implement this for `v0.2.0` yet. We should reopen it (or create separate issues) whenever we feel it's time to implement them.
