### ISSUE TITLE
Using Raw without alias requires a mix.clean to recover

### ISSUE THREAD

**Issue by cadebward** [msaraiva/surface#16]
I foolishly attempted to use `<#Raw></#Raw>` without first aliasing `Surface.Components.Raw`. As you might expect, this caused the component to break. Unfortunately, I was not able to recover from this error unless I stopped the server, ran `mix.clean`, and then started the server up again.

To reproduce, simply use `Raw` without the alias. Then, attempt to fix the issue by adding in the missing alias. The error should still exist.

I don't see this behavior when other errors occur. For example, I can attempt to use a component without first aliasing it. But, once I fix the alias, the error goes away and the component renders. It seems to only be happening with the `Raw` component.

**Comment by cadebward** [comment]
I think this may be related to #14

**Comment by msaraiva** [comment]
Hi @cadebward!

I can't reproduce the problem but I suspect I have to change the `#Raw` component to always generate an explicit `require` to avoid this problem. Can you please perform a simple test for me? 

1. without adding the alias, add the `<#Raw>...</#Raw>` component the same way you did before
2. compile the project to make sure it doesn't work
3. add the alias but this time, also add an explicit `require`. Like:

  ```
  alias Surface.Components.Raw
  require Raw
  ```
4. compile the project without cleaning it and see if it works as expected.

Let me know if it works so I can push a proper fix.

Thanks.

**Comment by cadebward** [comment]
I was not able to fix the issue by adding in a `require`. I also tried adding in the `require` first, then removing the alias. The component still get into a broken state and couldn't be recovered. 

Its interesting that you are not able to reproduce. I made my component as basic as possible: 
```ex
defmodule MyComponent do
  use Surface.Component

  alias Surface.Components.Raw
  require Surface.Components.Raw

  def render(assigns) do
    ~H"""
    <div>
      <#Raw>blarg</#Raw>
    </div>
    """
  end
end
```

Then, the containing component is as follows: 
```ex
defmodule Parent do
  use Surface.LiveView
  alias MyComponent

  def render(assigns) do
    ~H"""
    <div>
      <MyComponent />
    </div>
    """
  end
end
```

Note: They cannot be in the same file. Reloading the `Parent` module does fix the issue. Editing just the `MyComponent` module never puts `MyComponent` back into a working state. (I tried all scenarios with `require Raw` and without)

**Comment by msaraiva** [comment]
Thanks for the detailed report. I found out the problem can happen with any kind of component. It is exactly the same issue reported in #14. This [commit](https://github.com/msaraiva/surface/commit/092582341bf41c8efc6c4909f6e6c09f0d8cd402) fixed it. It should work just fine now.

Please let me know if any other issue.

Thanks again.

**Comment by cadebward** [comment]
@msaraiva Thanks! Confirmed that it works as expected now!
