### ISSUE TITLE
Surface UI website keeps on reloading in loop

### ISSUE THREAD

**Issue by kanmaniselvan** [msaraiva/surface#160]
Accessed http://surface-demo.msaraiva.io/ website on 17:29 - Monday, 12 October 2020 (CEST) for the documentation, but the site keeps on reloading in loop.

**Comment by msaraiva** [comment]
Hi @kanmaniselvan!

It has been reported that some people are having the same issue when accessing the website behind a proxy. Is there any error message on the browser console? Something like: 

`
WebSocket connection to ws://surface-demo.msaraiva.io/live/websocket?_csrf_token=...&_mounts=0&vsn=2.0.0 failed: Establishing a tunnel via proxy server failed.
`

The website will soon be moved to a new domain with proper `https` configured (not sure if this might be related). Until then, I’ll try is to see if it’s possible to fall back to long pooling if WebSockets fails.

**Comment by kanmaniselvan** [comment]
Hello @msaraiva, thanks for the reply.

I tried accessing now. This is the error that I see,

```js
app.js:3 
> WebSocket connection to 'ws://surface-demo.msaraiva.io/live/websocket?_csrf_token=DQREDiU9E2FDCTwWHzNJHhJIBVgeWw49aIqdMetV0mvbQA0Kt0C9Z2aZ&_mounts=0&vsn=2.0.0' failed: Invalid frame header
```

**Comment by kanmaniselvan** [comment]
Hello @msaraiva, thanks for the reply.

I tried accessing now. This is the error that I see,

```js
app.js:3 
> WebSocket connection to 'ws://surface-demo.msaraiva.io/live/websocket?_csrf_token=[filtered]&_mounts=0&vsn=2.0.0' failed: Invalid frame header
```

**Comment by kanmaniselvan** [comment]
Closing as the issue is fixed. Thanks, @msaraiva, for having a look.
