### ISSUE TITLE
Stateful vs Stateless components

### ISSUE THREAD

**Issue by margusp2heathmont** [msaraiva/surface#161]
Hello!

I have a **stateless component**, and gets in 1 prop as a String, that is assigned from parent. In parent it is set once in mount.

Altough the value does not change, on each render, data is sent over websockets.

By changing the component to be stateful (and assigning ID) - the data is not sent over websockets.

So my questions are: 
- if the input value from the parent to the child does not change and child itself is stateless - is it a bug or feature?
- are there any patterns where I can have stateless components optimised for not sending same data over network multiple times?

**Comment by msaraiva** [comment]
Hi @margusp2heathmont!

> * if the input value from the parent to the child does not change and child itself is stateless - is it a bug or feature?

I believe it's a feature of LV. As far as I know, stateless components are always updated when the parent changes. So in this regard, it's not very different from having a function. Stateful components, on the other hand, have their state tracked. I guess that's one of the reasons an `id` is required in the first place.

> * are there any patterns where I can have stateless components optimised for not sending same data over network multiple times?

LV only sends the dynamic parts so unless your component produces a lot of dynamic information, you should be fine. There are other things involved when it comes to performance so I guess you'll have to play around with your example and see what fits best.
