### ISSUE TITLE
Adding an options option to Surface.API

### ISSUE THREAD

**Issue by capitalist** [msaraiva/surface#163]
It may be called `options` or `meta` or `custom` - but here's the idea.

If a dev could add custom options to a surface property or slot, it enables extension of the API.

One use case might be adding a runtime validation schema as mentioned in #162

**Comment by msaraiva** [comment]
@capitalist I'm closing this in favour of https://github.com/msaraiva/surface/issues/162 so you can include this suggestion in the same discussion.
