### ISSUE TITLE
Cannot use Form components

### ISSUE THREAD

**Issue by iacobson** [msaraiva/surface#167]
version: `{:surface, git: "https://github.com/msaraiva/surface.git", tag: "v0.1.0-rc.0"}`
I have one `Surface.LiveView` and two `Surface.LiveComponent`
Everything went smooth until I tried to add a form to one of the live components
``` elixir
    <Form for={{ :move }} change="move">
      <Field name="position_degrees">
        <RangeInput value=50 min=0 max=100 step=1  />
      </Field>
    </Form>
```
I do not get a console error, but just a warning
`warning: cannot render <Form> (module Form could not be loaded)`
`lib/bsr_web/components/game/radar.ex:19: BSRWeb.Components.Game.Radar (module)`
There's nothing at line 19 that points to the Form, and also if I comment out the code, the warning remains there.
And in the browser:
<img width="449" alt="Screenshot 2020-10-20 at 20 28 18" src="https://user-images.githubusercontent.com/8473345/96629930-8d8c7c00-1314-11eb-9012-400522e5c72b.png">
(Radar is my module name)

I tried a few things:
- render just the Form with nothing inside
- render just the `RangeInput` without wrapping in Form
- move the form from live_component to the live_view
All resulted in the same behaviour. Eg: `module RangeInput could not be loaded`
- tried to use the `master` version of the package but got compilation errors

I mention that I use the `.sface` templates in case it matters.

**Comment by msaraiva** [comment]
Hi @iacobson!

This seems to be related to #166 which has been already merged. Can you try using the version on master? Make sure you `mix clean` before compiling again. A new `v0.1.0-rc.1` with that fix will be released later today. Please let me know if the problem persists.

Thanks!

**Comment by iacobson** [comment]
Hi and thanks for replying so quickly.
I already tried with master, but getting compilation error

```
mix deps.clean surface
mix deps.compile surface
==> surface
Compiling 81 files (.ex)

== Compilation error in file lib/surface/components/form/field.ex ==
** (ArgumentError) invalid runtime value for option :line in quote, got: nil
    (elixir 1.11.0) src/elixir_quote.erl:59: :elixir_quote.validate_runtime/2
    lib/surface/compiler/eex_engine.ex:730: Surface.Compiler.EExEngine.require_expr/2
    lib/surface/compiler/eex_engine.ex:638: Surface.Compiler.EExEngine.to_dynamic_nested_html/1
    lib/surface/compiler/eex_engine.ex:516: Surface.Compiler.EExEngine.to_dynamic_nested_html/1
    lib/surface/compiler/eex_engine.ex:577: Surface.Compiler.EExEngine.to_dynamic_nested_html/1
    lib/surface/compiler/eex_engine.ex:38: Surface.Compiler.EExEngine.to_token_sequence/1
    lib/surface/compiler/eex_engine.ex:27: Surface.Compiler.EExEngine.translate/2
    expanding macro: Surface.sigil_H/2
    lib/surface/components/form/field.ex:24: Surface.Components.Form.Field.render/1
    (elixir 1.11.0) lib/kernel/parallel_compiler.ex:314: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
could not compile dependency :surface, "mix compile" failed. You can recompile this dependency with "mix deps.compile surface", update it with "mix deps.update surface" or clean it with "mix deps.clean surface"
```

**Comment by iacobson** [comment]
Just pulled the latest master. The deps now compile.
The initial issue is still there, but now results in an error

```
== Compilation error in file lib/bsr_web/components/game/radar.ex ==
** (CompileError) lib/bsr_web/components/game/radar.sface:19: module Form is not loaded and could not be found
    (elixir 1.11.0) src/elixir_fn.erl:15: anonymous fn/4 in :elixir_fn.expand/3
    (stdlib 3.13) lists.erl:1354: :lists.mapfoldl/3
    (elixir 1.11.0) src/elixir_fn.erl:20: :elixir_fn.expand/3
    (stdlib 3.13) erl_eval.erl:680: :erl_eval.do_apply/6
```

**Comment by msaraiva** [comment]
@iacobson do you have a `alias Surface.Components.Form` in your `lib/bsr_web/components/game/radar.ex`?

**Comment by iacobson** [comment]
Thanks, my issue is now solved. I will close it

**Comment by msaraiva** [comment]
@iacobson thanks for reporting this issue. We should probably improve that message and add a hint. Something like:

```
warning: cannot render <Form> (module Form could not be loaded)

Hint: Make sure the module could be successfully compiled. 

If the module is namespaced, you can use its full name. For instance:

  <MyProject.Components.Form>

or add a proper alias so you can use just `<Form>`:

  alias MyProject.Components.Form
```

@lnr0626 WDYT?

**Comment by lnr0626** [comment]
Agreed - that would be a much better error message. 

Are we using the alias or the module name for the `<module> could not be loaded` error message? 

If we're using the alias instead of the expanded module name, we should consider switching to the expanded name so it's a bit easier to tell if it's a missing alias or a failure to compile. Thoughts?

**Comment by msaraiva** [comment]
There should be two messages in this case. One of the compilation error regarding the `require`, which we cannot update as it's a internal message from the Elixir compiler. The other one is a warning, which we can improve as much as we like. 

> Are we using the alias or the module name for the `<module> could not be loaded` error message?
> 
> If we're using the alias instead of the expanded module name, we should consider switching to the expanded name so it's a bit easier to tell if it's a missing alias or a failure to compile. Thoughts?

Currently, its the alias but I agree. We should have both in the message, like:

```
warning: cannot render <Form> (module MyProject.Component.Form could not be loaded)
```

**Comment by msaraiva** [comment]
Moving the discussion to its own issue #169.
