### ISSUE TITLE
Link component does not accept other components as children

### ISSUE THREAD

**Issue by miguel-s** [msaraiva/surface#168]
I'm running into issues when trying to pass a Surface component to the built-in `Link` component.

#### This works (inline svg)
```Elixir
<Link to="#" ...>
  <svg ...>
    ...
  </svg>
  Delete
</Link>
```

#### This gives an error (svg extracted into `Icon` component)
```Elixir
<Link to="#" ...>
  <Icon ...>
  Delete
</Link>
```

Just to be sure I also tried passing some built-in Surface components (e.g. `Label`) to make sure it's not being caused by my `Icon` component, but in all cases got the same error.

#### Full error log
```
ArgumentError at GET /transactions
cannot convert component Surface.Components.Form.Label with id nil to HTML.
A component must always be returned directly as part of a LiveView template.

For example, this is not allowed:

    <%= content_tag :div do %>
      <%= live_component @socket, SomeComponent %>
    <% end %>

That's because the component is inside `content_tag`. However, this works:

    <div>
      <%= live_component @socket, SomeComponent %>
    </div>

Components are also allowed inside Elixir's special forms, such as
`if`, `for`, `case`, and friends.

    <%= for item <- items do %>
      <%= live_component @socket, SomeComponent, id: item %>
    <% end %>

However, using other module functions such as `Enum`, will not work:

    <%= Enum.map(items, fn item -> %>
      <%= live_component @socket, SomeComponent, id: item %>
    <% end %>
```

**Comment by msaraiva** [comment]
Hi @miguel-s!

This is a limitation of LV and it's documented here https://hexdocs.pm/phoenix_live_view/Phoenix.LiveComponent.html#module-limitations. Any wrapper component like `Link` that ends up using `content_tag` under the hood will have this problem. 

There's not much we can do about it unless, of course, we roll our own implementations (like it was done for `LivePatch` and `LiveRedirect`).

**Comment by miguel-s** [comment]
Thanks @msaraiva!

**Comment by msaraiva** [comment]
I'm reopening this as I believe we should roll our own `<Link>` implementation that does not depend on link/content_tag.

**Comment by msaraiva** [comment]
Closing this in favour of #262
