### ISSUE TITLE
Compiler warning on defmodule line with catch-all handle_event

### ISSUE THREAD

**Issue by brainlid** [msaraiva/surface#17]
Here's a weird one that took me some time to isolate.

```elixir
defmodule Empty do
  use Surface.LiveComponent
  require Logger

  def render(assigns) do
    ~H"""
    <div class="blank">
    </div>
    """
  end

  def handle_event(event, _data, socket) do
    Logger.warn("Unhandled event #{event}")
    {:noreply, socket}
  end
end
```

This results in the following 2 errors: (I edited the error text for file paths)

```
warning: this clause cannot match because a previous clause at line 1 always matches
  lib/empty.ex:1
```

This puts a compiler warning on the `defmodule` line. It appears to swallow the actual line with the issue.

If you really don't want to allow a "catch-all" `handle_event`, then perhaps give a more specific error.

**Comment by msaraiva** [comment]
@brainlid thanks for reporting this issue. I will fix it together with the [new API for events](https://github.com/msaraiva/surface/issues/20).
