### ISSUE TITLE
:if and :for on <slot>

### ISSUE THREAD

**Issue by paulstatezny** [msaraiva/surface#173]
Currently this is not possible, but I think it would be useful in certain scenarios:

```html
<slot :if={{ @foo }} />
```

Also, you'd asked me to include a note about adding `:for` as well:

```html
<slot :for={{ item <- @items }} />
```

Thanks!

**Comment by msaraiva** [comment]
Yeah, I don't see any reason to not include them. @lnr0626 do you see any limitation?

**Comment by lnr0626** [comment]
originally slot directives were handled differently, but that was changed a bit ago - this should be simply a matter of adding them to the [`@slot_directive_handlers` list](https://github.com/msaraiva/surface/blob/master/lib/surface/compiler.ex#L42) as the second and third elements (if then for to keep the ordering consistent with the other ones)

We could potentially add debug in there as well, though that may require some additional changes to the eex_engine to get the `:code` option working.
