### ISSUE TITLE
:for.with_index not working on Surface components

### ISSUE THREAD

**Issue by paulstatezny** [msaraiva/surface#175]
It seems that `:for.with_index` works when used in native HTML elements, but not Surface components.

For example, this works:

```html
<div :for.with_index={{ {button, i} <- @buttons }}>
  <Button>...</Button>
</div>
```

But this doesn't:

```html
<Button :for.with_index={{ {button, i} <- @buttons }}>
  ...
</Button>
```

**Comment by msaraiva** [comment]
I created a test for it and can confirm it's a bug. Working on it. Thanks!
