### ISSUE TITLE
https://github.com/msaraiva/surface/tree/scoped-styles

### ISSUE THREAD

**Issue by margusp2heathmont** [msaraiva/surface#179]
Hello!

Would it be possible to update it, to support <Context /> and "prop" keyword and same LiveView version as on Surface master?

**Comment by msaraiva** [comment]
Hi @margusp2heathmont!

I'm currently implementing some changes in this proposal as I'm moving all related code to a separate project. With the new project (temporally called `surface_scoped_styles`), people will be able to add this feature to any existing project and make their own experiments. I'll ping you as soon as it's available.
