### ISSUE TITLE
Non-closing tags with directive fail.

### ISSUE THREAD

**Issue by saverio-kantox** [msaraiva/surface#18]
A tag like the following (which I wanted to use as first information in a table where the first visible header row does not have all the columns)
```html
<col :for={{ c <- @cols }}>
```
fails to be parsed.

Full context:
```html
<table>
  <col :for={{ _ <- @cols }}>
  <thead>
    <tr><th colspan="99">This row only has one cell, so table layout would fail without the COL tags.</th></tr>
    <tr><th :for={{ c <- @cols }}>{{ c.title }}</th></tr>
  </thead>
  ....
</table>
```

**Comment by saverio-kantox** [comment]
The only solution I have found is to define a very simple component
```ex
defmodule Col do
  def render(assigns) do
    ~H"""
    <col>
    """
  end
end
```

and then use it as a self-closing component:
```html
<table>
  <Col :for={{ _ <- @cols }} />
  <thead>...
```

**Comment by msaraiva** [comment]
Fixed in https://github.com/msaraiva/surface/commit/4e5137891f865fd5030cdc7f1c341d678bb78442

@saverio-kantox thanks for reporting this issue!
