### ISSUE TITLE
Typed slotables don't appear when generated with `:for`

### ISSUE THREAD

**Issue by paulstatezny** [msaraiva/surface#182]
Hello! I'm experiencing some unexpected behavior.

## Example Scenario

Let's assume this oversimplified component:

```elixir
defmodule MyList do
  use Surface.Component

  defmodule Item do
    use Surface.Component, slot: "items"
  end

  def render(assigns) do
    ~H"""
    <ul>
      <li :for.with_index={{ {_item, i} <- @items }}>
        <slot name="items" index={{ i }} />
      </li>
    </ul>
    """
  end
end
```

It's used like this:

```eex
<MyList>
  <MyList.Item>Apple</MyList.Item>
  <MyLst.Item>Orange</MyList.Item>
  <MyList.Item>Kiwi</MyList.Item>
</MyList>
```

Which emits:

```html
<ul>
  <li>Apple</li>
  <li>Orange</li>
  <li>Kiwi</li>
</ul>
```

## Unexpected behavior with dynamically-generated typed slotables

If you create `<MyList.Item>`s dynamically with `:for` instead, like this:

```elixir
<MyList>
  <MyList.Item :for={{ item <- ["Apple", "Orange", "Kiwi"] }}>
    {{ item }}
  </MyList.Item>
</MyList>
```

It crashes on this line:

```elixir
<li :for.with_index={{ {_item, i} <- @items }}>
```

with this error:

```
assign @items not available in eex template.
```

It's as if the component with `:for` is completely ignored by the compiler. (Same error as if I just render `<MyList></MyList>`)

## Summary

It seems with typed slotables you are required to hard-code content; you cannot dynamically create them using `:for`.

Is this intended? Is there a path to support this? Thank you!

**Comment by msaraiva** [comment]
> It seems with typed slotables you are required to hard-code content; you cannot dynamically create them using `:for`.

Yup. Slots must be hard-coded as we need to handle them at compile-time. The generated code for `:for` will only be executed at runtime so, currently, there's no way to achieve that.

To achieve something similar it would require a new directive or maybe a macro component that could evaluate the expression at compile-time (note: that would require the values to be all literals as in your example) and then take the result and manipulate Surface's AST.

@lnr0626 we should probably warn or even raise an error if the user tries to use `:for` or any incompatible directive on a renderless component.

**Comment by msaraiva** [comment]
@paulstatezny BTW, `:for` also has an `index` modifier so instead of:

```jsx
<li :for.with_index={{ {_item, i} <- @items }}>
  <slot name="items" index={{ i }} />
</li>
```

you can do:

```jsx
<li :for.index={{ i <- @items }}>
  <slot name="items" index={{ i }} />
</li>
```

or even:

```jsx
<li :for.index={{ @items }}>
  <slot name="items" index={{ index }} />
</li>
```

if you prefer :)

**Comment by paulstatezny** [comment]
Ok, thanks for the fast response! Sounds like it's in conflict with fundamental aspects of how the compiler works to do this completely dynamically. I definitely would 

> To achieve something similar it would require a new directive or maybe a macro component that could evaluate the expression at compile-time (note: that would require the values to be all literals as in your example) and then take the result and manipulate Surface's AST.

I'm pretty confident I'd use this. 😃

**Comment by paulstatezny** [comment]
To anyone stumbling upon this, here's my workaround for this scenario:

```elixir
defmodule MyList do
  use Surface.Component

  prop items, :list

  def render(assigns) do
    ~H"""
    <ul>
      <li :for={{ item <- @items }}>
        {{ item }}
      </li>
    </ul>
    """
  end
end
```

```elixir
<MyList items={{ ["Apple", "Orange", "Kiwi"] }} />
```

**Comment by msaraiva** [comment]
@paulstatezny I'm closing this in favour of #189.

We can evaluate the possibility of adding a static `<For>` or maybe adding a property `static` to it later when we have more examples of its use.
