### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by jburky** [msaraiva/surface#186]
While following the install instructions from the README.md I received the following error while running `mix deps.get`:

* Getting surface (https://github.com/msaraiva/surface.git - v0.1.0-rc.1)
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 3101 (delta 3), reused 7 (delta 3), pack-reused 3084
Receiving objects: 100% (3101/3101), 1.06 MiB | 5.71 MiB/s, done.
Resolving deltas: 100% (2201/2201), done.
Dependencies have diverged:
* phoenix_live_view (Hex package)
  the dependency phoenix_live_view in mix.exs is overriding a child dependency:

  > In mix.exs:
    {:phoenix_live_view, "~> 0.14.6", [env: :prod, repo: "hexpm", hex: "phoenix_live_view"]}

  > In deps/surface/mix.exs:
    {:phoenix_live_view, [env: :prod, git: "https://github.com/phoenixframework/phoenix_live_view.git", tag: "597c5ddf8af2ca39216a3fe5a44c066774de3abd"]}

  Ensure they match or specify one of the above in your deps and set "override: true"
** (Mix) Can't continue due to errors on dependencies

**Comment by msaraiva** [comment]
Hi @jburky!

Do you have both, `:phoenix_live_view` and `:surface` as dependencies in your `mix.exs`? If so, can you try to remove `:phoenix_live_view` and let just `:surface` there? Then run `mix deps.get` and compile again.

Please let me know it works. If it does, I'll update the README and add a note about this. I believe this can only be properly fixed after LV `v.0.15` is out.

**Comment by jburky** [comment]
Got a similar error with dashboards:

* Updating phoenix_live_view (https://github.com/phoenixframework/phoenix_live_view.git - 597c5ddf8af2ca39216a3fe5a44c066774de3abd)
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  connection 1.0.4
  cowboy 2.8.0
  cowboy_telemetry 0.3.0
  cowlib 2.9.1
  db_connection 2.3.0
  decimal 2.0.0
  earmark 1.4.10
  earmark_parser 1.4.10
  ecto 3.5.4
  ecto_sql 3.5.3
  file_system 0.2.9
  floki 0.29.0
  gettext 0.18.2
  html_entities 0.5.1
  jason 1.2.2
  mime 1.4.0
  nimble_parsec 0.5.3
  phoenix 1.5.6
  phoenix_ecto 4.2.1
  phoenix_html 2.14.2
  phoenix_live_dashboard 0.3.6
  phoenix_live_reload 1.2.4
  phoenix_live_view 0.14.8
  phoenix_pubsub 2.0.0
  plug 1.11.0
  plug_cowboy 2.4.1
  plug_crypto 1.2.0
  postgrex 0.15.7
  ranch 1.7.1
  telemetry 0.4.2
  telemetry_metrics 0.6.0
  telemetry_poller 0.5.1
Dependencies have diverged:
* phoenix_live_view (https://github.com/phoenixframework/phoenix_live_view.git - 597c5ddf8af2ca39216a3fe5a44c066774de3abd)
  different specs were given for the phoenix_live_view app:

  > In deps/surface/mix.exs:
    {:phoenix_live_view, [env: :prod, git: "https://github.com/phoenixframework/phoenix_live_view.git", tag: "597c5ddf8af2ca39216a3fe5a44c066774de3abd"]}

  > In deps/phoenix_live_dashboard/mix.exs:
    {:phoenix_live_view, "~> 0.14.3", [env: :prod, hex: "phoenix_live_view", repo: "hexpm", optional: false]}

  Ensure they match or specify one of the above in your deps and set "override: true"
** (Mix) Can't continue due to errors on dependencies

**Comment by msaraiva** [comment]
Thanks for the extra info!

Surface is not compatible with LV `v0.14.6` so I believe you'll have to add `:phoenix_live_view` using `override: true`:

```
  defp deps do
    [
      ...

      {:phoenix_live_view,
       git: "https://github.com/phoenixframework/phoenix_live_view.git",
       tag: "f986171cae03747366c3cd1c4f4fea047e1d7196",
       override: true},
      {:surface, 
       git: "https://github.com/msaraiva/surface.git", 
       tag: "b745e1322ce7b20fcbcf8503f507349da0772435"},
    ]
  end
```

However, the question is whether the version of `phoenix_live_dashboard` you're using will be compatible with the latest LV changes on master.

BTW, I'll release `v0.1.0-rc.2` later today so you'll be able to use the following instead:

```
{:surface, git: "https://github.com/msaraiva/surface.git", tag: "v0.1.0-rc.2"}
```

**Comment by msaraiva** [comment]
@jburky version `v0.1.0-rc.2` has just been released. Feel free to give it a try and let me know if you find any issues.

**Comment by msaraiva** [comment]
In case anyone needs to use both, `Surface` and `Phoenix LiveDashboard`, there's already a fork with the proper fixes  https://github.com/BlinkerGit/phoenix_live_dashboard/tree/0.3.6-0.15-dev.

**Comment by jburky** [comment]
@msaraiva That's great news. I will try and give it a go later today.

**Comment by mindreframer** [comment]
@msaraiva I just tried it out, and is seems to still fail... 
Here is a reproducible project with the bug: https://github.com/happycodrz/failing_assigns_with_surface
Plain phx app + surface. Hope this helps to narrow the problem down. And: thanks for this great library, really looking to try it out on my next project!

**Comment by mindreframer** [comment]
@msaraiva Just saw the link to `https://github.com/BlinkerGit/phoenix_live_dashboard/tree/0.3.6-0.15-dev` -> this fork works properly!

**Comment by jessejanderson** [comment]
@msaraiva are these fixes going to be coming to `phoenix_live_dashboard` eventually so that we don't have to rely on a fork?

**Comment by msaraiva** [comment]
@jessejanderson the fixes present in the fork are related to changes in LV's API, so yes, they must be eventually merged upstream, otherwise, it won't work with LV `>= v0.15`.
