### ISSUE TITLE
Compile Errror: undefined function render_block/2

### ISSUE THREAD

**Issue by mcgingras** [msaraiva/surface#187]
Just trying to get this library off the ground and running.

Compilation error in file lib/surface/components/form/submit.ex ==
** (CompileError) lib/surface/components/form/submit.ex:40: undefined function render_block/2
    (elixir 1.10.1) src/elixir_locals.erl:114: anonymous fn/3 in :elixir_locals.ensure_no_undefined_local/3
    (stdlib 3.11.2) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.10.1) lib/kernel/parallel_compiler.ex:233: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7

**Comment by msaraiva** [comment]
Hi @mcgingras!

Can you show the list the dependencies you have in your `mix.exs` and which versions are being used in `mix.lock`? I believe you're using Surface with an older version of `phoenix_live_view`.

**Comment by mcgingras** [comment]
Sure! 

Although it's worth mentioning that after initially getting the error I tried to boot up a fresh project with `mix phx.new my_app --live` and I got the same issue. So even with out of the box dependancies I was experiencing this issue.

In the more mature project in which I was trying to include surface I have a big long list of deps, but my `phoenix_live_view` version is `~> 0.14.7`

**Comment by msaraiva** [comment]
Hey @mcgingras!

Surface in not complatiable with LV `v0.14.7`.

Can you please try using `override: true` as explained here https://github.com/msaraiva/surface/issues/186#issuecomment-721142721 ?

**Comment by msaraiva** [comment]
@mcgingras Surface `v0.1.0-rc.2` has just been released. Try to remove the existing `phoenix_live_view` (if any) from your dependencies and add:

```
{:surface, git: "https://github.com/msaraiva/surface.git", tag: "v0.1.0-rc.2"}
```

Please let me know if you run into any issue.

Cheers.

**Comment by mcgingras** [comment]
Hi @msaraiva!

I tried removing `phoenix_live_view` but other dependencies also relied on it or reference it themselves, and they use different versions than Surface.

Might it be easier to keep `phoenix_live_view` but specify the version Surface expects?

**Comment by msaraiva** [comment]
> Might it be easier to keep `phoenix_live_view` but specify the version Surface expects?

It might work but it will depend whether `oban_web` is compatible with the recent changes in LV or not.

This works for Surface:

```
{:phoenix_live_view,
       git: "https://github.com/phoenixframework/phoenix_live_view.git",
       tag: "f986171cae03747366c3cd1c4f4fea047e1d7196",
       override: true}
```

Not sure about `oban_web` though. In case it's not compatible, you could take a look and see if there's already a PR to make it work with LV `0.15.0-dev`.

**Comment by mcgingras** [comment]
Great, I will try this out. Thanks for the help @msaraiva!
