### ISSUE TITLE
Data assigns don't work with `assign_new/3`

### ISSUE THREAD

**Issue by miguel-s** [msaraiva/surface#192]
Hi!

It seems that declaring `data` assigns does not play well with LiveView's `assign_new/3`.

Surface automatically initializes all `data` assigns with their default value or nil, while `assign_new/3` only checks for the existence of the key in the socket assigns. This results in `assign_new/3` never actually assigning a value to the socket.

You can see a small example of this behaviour when trying to implement this LiveView guide with Surface: https://hexdocs.pm/phoenix_live_view/security-model.html#mounting-considerations

Using Surface the following part will not work and leave `current_user` with the value `nil` (or default value if specified):

```JS
socket = assign_new(socket, :current_user, fn -> Accounts.get_user!(user_id) end)
```

**Comment by msaraiva** [comment]
I believe we have at least two options to fix this:

1. If the `data` assign is declared without a `default` option, we don't initialize it. This will break any existing code that assumes the data will be present.
1. We keep the current behaviour and add a new option to not initialize the value, e.g:
`data current_user, :string, init: false`

@lnr0626 any other ideas?

**Comment by lnr0626** [comment]
Those are the first two thoughts that pop into my head. I'd kind of expected the behaviour to be closer to 1 to work well with `assign_new`

**Comment by miguel-s** [comment]
This is probably a bad idea, but just to mention option 3: provide a `before_init` hook where it's possible to access the socket before Surface initializes data assigns.

**Comment by msaraiva** [comment]
@miguel-s I wonder why you think it's a bad idea. I think option `#1` is probably our best shot as it keeps the default behaviour of live views and components and only when adding `default`, we do something different.

**Comment by miguel-s** [comment]
@msaraiva agree with your assessment of option 1, and those are the same reasons why I think option 3 is not good (different behaviour to LiveView and adds an unexpected workaround)
