### ISSUE TITLE
Dynamic props

### ISSUE THREAD

**Issue by msaraiva** [msaraiva/surface#2]
Similar to React but with valid Elixir syntax:

```jsx
<Component {{..., props}} foo="override" />
```

**Comment by msaraiva** [comment]
It could also be a directive. Something like:

```jsx
<Component :props={{ props }} foo="override" />
```

**Comment by mazz-seven** [comment]
Hey,
Amazing work on Surface. Coming from React is was hard for me to develop with EEX. 
If you need any help, I will do my best to contribute. 

What do you mean dynamic props? The syntax looks like the spread operation in javascript.

**Comment by msaraiva** [comment]
> What do you mean dynamic props? The syntax looks like the spread operation in javascript.

Yup. That's exactly what it is. Currently, if you need to pass properties you need to know all of them up front. There's no way to pass a different set of properties to the same component. React can achieve that using a syntax that maps the spread operator:

```jsx
<div {...this.myprops} />
```
Vue can also do that by using `v-bind`:

```vue
<div v-bind="myprops"></div>
```

This is very handy especially when you have a component that just sets a few properties of an existing one, but keeps all available props to the user to be overridden. Without this feature, we need to forward all properties to the child component by passing each one of them manually again.

So the first suggestion makes it similar to React, the second one makes it similar to Vue.js, which could be implemented as a directive `:props`. The Vue-like solution would be easier since it doesn't require changes in the parser.

A hypothetical example would be something like:

```elixir
defmodule EnhancedButton do
  use Surface.Component

  import_props from: Button 

  def render(assigns) do
    ~H"""
    <Button :props={{ @props }} style="...">
      {{ @inner_content.() }}
    </Button>
    """
  end
end
```

The suggested `import_props` is important in this case so we have a way to keep the static checking of properties.

**Comment by mazz-seven** [comment]
Taking into account that there is no spread operation in Elixir. I think the :props={{ props }} is nicer and if it's easier to implement it's a big plus.

Would it be possible to use some of the props in the parent component and only pass a subset of the props to the child?

**Comment by msaraiva** [comment]
Sure! We could even have something that looks like the original `import` (except for the `as`):

```elixir
import_props Button, only: [:label]
import_props Button, except: [:label], as: :props
```
and then

```jsx
<Button :props={{ @props }}>
  {{ @label }}
</Button>
```

This way we could keep the static checking for most common cases, I guess.

**Comment by neilberkman** [comment]
Is there currently any way to include a boolean attribute like `disabled` conditionally? Vue lets you do something like `:disabled="disabled == 1"` so I tried `:disabled={{ @disabled }}` and it doesn't seem to work.

**Comment by brainlid** [comment]
@neilberkman If I understand your question correctly, then the answer is "yes". 

See the sample docs here: http://surface-demo.msaraiva.io/getting_started

Specifically there is an example under "CSS class property". It shows the idea of passing a boolean value this way:

```elixir
  <MyButton loading={{ @loading }} rounded={{ @rounded }}>
    Change my style using the checkboxes below!
  </MyButton>
```

**Comment by neilberkman** [comment]
Thanks for responding. I'm asking about [boolean attributes](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes) such as `disabled`:

> Note: The values "true" and "false" are not allowed on boolean attributes. To represent a false value, the attribute has to be omitted altogether.

When I try your suggestion:

```html
<input type="submit" value="Delete" disabled={{ false }}>
```

...I get an attribute with a boolean value in the case in which the attribute shouldn't be present at all:

```html
<input type="submit" value="Delete" disabled="false">
```

I'm looking to find some clean way of making the inclusion of the attribute conditional. Also, sorry if I hijacked this issue. It seems like dynamic properties might be a way to do what I want, although not necessarily the cleanest.

**Comment by msaraiva** [comment]
> Is there currently any way to include a boolean attribute like disabled conditionally?

@neilberkman now there is! 😜

Added in https://github.com/msaraiva/surface/commit/da223087b056a39e73dae48184c385b467141719.

You can do this now:

```vue
<input type="submit" value="Delete" disabled={{ @disabled }}>
```

**Comment by msaraiva** [comment]
> Pay attention that `@disabled` must be a boolean, not a string.

I decided to change this behaviour. Now It accepts any value and if the value is truthy, it shows the attribute.

**Comment by neilberkman** [comment]
Awesome, thanks so much for adding this!

**Comment by zamith** [comment]
I have a question that is tangentially related to this, so I'll ask here.

I want to pass a map/struct to a component, and I know which fields I need in the component, but I don't want the parent to have to care about it necessarily. Is there any way to check that a map has the correct fields from the child at compile time?

This would be similar to `PropTypes` `shape`. Here's an example:

```elixir
defmodule Parent do
  use Surface.LiveView

  def render(assigns) do
    ~H"""
    <Child :for={{ elem <- @collection }} elem={{ elem }} />
    """
  end

  ...
end

defmodule Child do
  use Surface.Component

  property elem, :map, required: true
  ...
  def render(assigns) do
    ~H"""
    <p>{{ @elem.field1 }}</p>
   <p>{{ @elem.field2 }}</p>
    """
  end
end
```

The idea here being that `Child` could be able to tell the map's shape. Something like:

```
property elem, :map, required: true, shape: %{ field1: :string, field2: :boolean }
property elem, :map, required: true, shape: SomeStruct
```

What do you think?

**Comment by msaraiva** [comment]
Hi @zamith!

The problem is that the value of `elem` is only known at runtime, so compile-time checking would require a real type system for inference which is something Elixir doesn't have yet. What Surface can do in some situations is to validate fields that are explicitly defined. 

For instance, the new `slot` feature allows users to pass props to the parent scope like:

```elixir
...

property min, :integer, default: 0
slot value, props: [:value, :min] # <-- The list of accepted props
data value, :integer, default: 0

...

render(assigns) do
  ~H"""
  ...
  <div>
    <slot :props={{ value: @value, mini: @min }} />
  </div>
  """
end
```

Surface can validate that prop `mini` does not exist and raise a compile-time error because the value of `:props` is a literal keyword list where the fields were explicitly defined. However, if we want to pass it as a variable, e.g.:

```jsx
 <slot :props={{ @props }} />
```
Surface will not be able to validate statically because the value of `@props` will only be available at runtime.

**Comment by msaraiva** [comment]
Just for completeness, in:

```elixir
<p>{{ @elem.field1 }}</p>
```

It's quite easy to validate `field1` against the list of accepted values if we only consider expressions in the `{{ @elem.field1 }}`format. I even thought of adding this feature before, however, since `{{ }}` accepts any expression, if we want to validate all of them, we would need to traverse the code inside `{{ }}` and search for `@elem.` deep in the AST tree. It's doable but I'm not sure how that would impact performance and if there would be tricky edge cases.

It would be certainly a very nice feature :)

**Comment by zamith** [comment]
Is there any interest in validating it at runtime then? I mean, it's likely this would result in an error, but fail silently. Validation, even at runtime would prevent this.

At the same time, it's something that a developer might miss an blow up for a client/user, so not sure.

**Comment by zamith** [comment]
Regarding dynamic props, I think that the proposed solution works well when you know the props somewhere down the chain (in this case Button).

```elixir
defmodule EnhancedButton do
  use Surface.Component

  import_props from: Button 

  def render(assigns) do
    ~H"""
    <Button :props={{ @props }} style="...">
      {{ @inner_content.() }}
    </Button>
    """
  end
end
```

What about wanting to pass props along to an HTML element that is not defined as a surface component, for example:

```
defmodule Button do
  use Surface.Component

  props click, :event

  def render(assigns) do
    ~H"""
    <button :on-phx-click={{ @click }}  :props={{ @props }}>
      {{ @inner_content.() }}
    </button>
    """
  end
end
```

Would this be a possibility? I understand we'd lose the compile time checks, but I guess that's what we want in this case for forward compatibility, right?

**Comment by izzues** [comment]
Is there some way to emulate `import_props` for now except by manually declaring common props in all components? It would come in really handy :)

**Comment by msaraiva** [comment]
Hi @izzues!

For now, you could use a macro. Something similar to what we do [here](https://github.com/msaraiva/surface/blob/master/lib/surface/components/form/input.ex#L11-L39) for the input controls. However, if you just want to add common properties without adding any extra code, you don't need to implement `__using__`. A regular macro will do the trick.
