### ISSUE TITLE
Why are we pinning a specific version of live view?

### ISSUE THREAD

**Issue by zoidbergwill** [msaraiva/surface#201]
Trying to use this for a new Phoenix project, since I'd love to use it on top of live view for a new project, since it's been amazing on other projects, but unfortunately it's causing a bit of a headache because of the pinning of the commit for phoenix_live_view.

I tried removing my own dependency on live view, but then the diamond dependency issue is between surface and phoenix live dashboard, and I'd love to use both.

**Comment by msaraiva** [comment]
Hi @zoidbergwill!

Until both, LiveView `v0.15` and a compatible Live Dashboard version is out, the only way to use both is using a fork as suggested here https://github.com/msaraiva/surface/issues/186#issuecomment-721822779.

**Comment by zoidbergwill** [comment]
My bad. I should've looked harder for a similar issue.

Thanks for the quick helpful polite response!
