### ISSUE TITLE
Disable validation for required props when using :props

### ISSUE THREAD

**Issue by msaraiva** [msaraiva/surface#202]
I have a case where I need to do something like:

```jsx
<MyComponent :props={{ @props }}/>
```

The problem is that `MyComponent` defines some required props and although the implementation guarantees that `@props` will contain all required props, the static validator will warn about them since they are not explicitly passed.

The simplest solution would be to automatically disable the static validation whenever `:props` is used. The downside is that we're losing this validation for all scenarios even though in most cases the set of explicit props and the dynamic props will be mutually exclusive, which would allow the validation to run correctly.

@lnr0626 do you see any alternative?

**Comment by lnr0626** [comment]
The only alternative I see right now is supporting something like what we're discussing in #162 with allowing users to specify the structure of a prop - that would allow us to see that `@props` had the capability of supplying the required props at compile time and disable the warning in that case.
