### ISSUE TITLE
style="background-image: url(https://example.com/breaks.jpg)"

### ISSUE THREAD

**Issue by margusp2heathmont** [msaraiva/surface#203]
error at:
lib/surface/type_handler/style.ex:10: anonymous fn/2 in Surface.TypeHandler.Style.expr_to_value/2

**Comment by msaraiva** [comment]
Fixed in https://github.com/msaraiva/surface/commit/be47d5a87d9b244f39651cfa91e3d6457f829d57.

@margusp2heathmont thanks for reporting it!
