### ISSUE TITLE
Helper to know if a slot has been filled

### ISSUE THREAD

**Issue by Malian** [msaraiva/surface#206]
In my component I have a wrapper around an optional slot.

```html
<div class="border-b border-gray-200 px-4 py-4 flex items-center justify-between sm:px-6 lg:px-8">
  <div class="flex-1 min-w-0 py-2">
    <h1 class="text-lg font-medium leading-6 text-gray-900 sm:truncate">
      {{ @page_title }}
    </h1>
  </div>
  <div class="flex">
    <slot name="right"/>
  </div>
</div>
```
As the slot is optional, if the user does not fill it, the result contains an empty `div`:
```html
<div class="flex">
</div>
```

I would like to remove this empty `div` by knowing if the slot has been filled. Today I created a helper for this:
```elixir
  defp has_slot?(%{__surface__: %{provided_templates: slots}}, slot) do
    slot in slots
  end

  defp has_slot?(_, _), do: false
```
And I use it like that
```html
<div class="border-b border-gray-200 px-4 py-4 flex items-center justify-between sm:px-6 lg:px-8">
  <div class="flex-1 min-w-0 py-2">
    <h1 class="text-lg font-medium leading-6 text-gray-900 sm:truncate">
      {{ @page_title }}
    </h1>
  </div>
  <div class="flex" :if={{ has_slot?(assigns, :right) }}>
    <slot name="right"/>
  </div>
</div>
```

Does Surface have a more idiomatic way to know is a slot has already been filled? If not, what about adding a helper in Surface?

I would be happy to implement this feature if you wish.

**Comment by msaraiva** [comment]
Hi @Malian!

Since named slots are stored as assigns, you can do the following:

```jsx
<div class="flex" :if={{ assigns[:right] }}>
  <slot name="right"/>
</div>
```

However, I agree we could have a more explicit way to do that. Maybe we should create a macro so we could additionally be able to validate at compile-time if the slot has been declared or not. I'm not sure about the name though because in this case, we actually have a slot (it has been defined by the `<slot>` tag). It just hasn't been filled yet so `has_slot?` might be misleading. Here're some alternatives suggestions:

```jsx
<div :if={{ slot_filled?(:right) }}>
```

```jsx
<div :if={{ slot_assigned?(:right) }}>
```

@lnr0626 any other suggestion?

**Comment by lnr0626** [comment]
`has_slottable?(:name)` or `slottable?(:name)` is consistent with the terminology on mdn about slots (https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_templates_and_slots and https://developer.mozilla.org/en-US/docs/Web/API/Slottable); though I've found that terminology to be a little bit confusing.

**Comment by Malian** [comment]
Thank you both for your prompt responses.

@msaraiva In the beginning, I had indeed used `assigns[:right]` to check whether the slot had been filled or not. Two weeks later I went back to my code and I no longer understood this condition. What was my intention? I understand that "slots" are stored in `assigns` from a technical point of view but it seems strange from a DX point of view. So I decided to use the `provided_templates` key because it seems more explicit in context and better describes my intentions.

I am willing to spend some time on this feature if you wish. In that case, could you quickly walk me through the steps needed to get things done?

**Comment by msaraiva** [comment]
> I am willing to spend some time on this feature if you wish. In that case, could you quickly walk me through the steps needed to get things done?

Sure. Something like this should work:

```elixir

  alias Surface.API
  alias Surface.IOHelper

  defmacro slot_assigned?(slot) do
    defined_slots = API.get_slots(__CALLER__.module) |> Enum.map(& &1.name)

    if slot not in defined_slots do
      IOHelper.warn("Undefined slot #{inspect(slot)}", __CALLER__, & &1)
    end

    quote do
      unquote(__MODULE__).slot_assigned?(var!(assigns), unquote(slot))
    end
  end

  @doc false
  def slot_assigned?(%{__surface__: %{provided_templates: slots}}, slot) do
    slot in slots
  end

  def slot_assigned?(_, _), do: false
```

You can add the code above to `lib/surface.ex` so the macro can be imported by default.

And optionally, If you really want to shine here, you can improve the warning message doing something similar to: https://github.com/msaraiva/surface/blob/911a73e705795232523e703998c2ae47e188fa6c/lib/surface/compiler.ex#L719-L747

**Comment by lnr0626** [comment]
One thing to note is that the default slot's name in the `provided_templates` map is `:__default__`

**Comment by msaraiva** [comment]
@lnr0626 good point. Maybe we should do something about that too. The main reason we use `:__default__` is to keep the name `:default` available as it might be a common name for a property, however, I think this solution is inconsistent as it does not prevent other good names from falling into the same problem. Ideally, we could have an optional option `:as` for slots that would be used to name the assign. Something like:

```elixir
# Defines a :default assign (not :__default__)
slot default

# Defines a :default_slot assign if you want to reuse :default as a property
slot default, as: :default_slot
```

This would make the behaviour of all slots, named or not, consistent.

@Malian no need to do this in the scope of this PR as it may require a few changes in many different places.
