### ISSUE TITLE
Strings with double quotes passed to `data-*` attributes stops at first `"` in the JS hook

### ISSUE THREAD

**Issue by code-shoily** [msaraiva/surface#216]
I tried passing a JSON string as `data-*` attribute to JSON and when the JavaScript hook tried doing `JSON.parse` it threw an error. Upon inspection I found out that if I pass any value with double quote (") in it, then the hook receives all value until the first occurence of the quote. Here are the examples:

The following sends only `[{` to JS instead of full string:

```
  def render(assigns) do
    ~H"""
    <div id="hook" phx-hook="SurfaceHook" data-coords={{ Jason.encode!([%{x: 10, y: 20}]) }}>
      {{ Jason.encode!([%{x: 10, y: 20}]) }}
    </div>
    """
  end
```

The equivalent `LiveView` code that works:

```
  def render(assigns) do
    ~L"""
    <div id="hook" phx-hook="SurfaceHook" data-coords="<%= Jason.encode!([%{x: 10, y: 20}]) %>">
      Hello Surface
    </div>
    """
  end
```

The code in JS hook where the error takes place:

```
var Hooks = {
    SurfaceHook: {
        mounted() {
            var value = this.el.dataset.coords;
            console.log({ value }); // <-- is "[{"
            JSON.parse(value) // <-- throws Error
        }
    }
}
```

What is the correct way of doing this with surface component?

**Comment by msaraiva** [comment]
@code-shoily thanks for reporting this issue. I'm working on the fix now and should release a patch version today.

**Comment by msaraiva** [comment]
@code-shoily Surface `v0.1.1` has just been release. Please let me know if still find any issue.

Cheers.
