### ISSUE TITLE
Support loading external templates and css files

### ISSUE THREAD

**Issue by msaraiva** [msaraiva/surface#22]
Implement a default `render/1` that automatically loads files with the same base name + `.sface` and `.css`. 

Example:

```
live/
├── components/
│   ├── card.css
│   ├── card.ex
│   ├── card.sface
│   ├── hero.css
│   ├── hero.ex
│   └── hero.sface
│
...
```

For `*.sface` files, the implementation is straightforward, however, for `*.css` we should probably wait until we have scoped styles (#1).

**Comment by msaraiva** [comment]
I believe `.sface` files could also be used as layouts. However, I'm not sure if this would require changes in phoenix.

**Comment by joshuataylor** [comment]
What about `card.html.sface` for templates?

**Comment by msaraiva** [comment]
Hi @joshuataylor!

Using `.html.sface` instead of just `.sface` is probably redundant. Unlike `EEX`, which works with any kind of text, Surface requires the source code to be a valid structured Surface file, which is basically an extended version of HTML.
