### ISSUE TITLE
Select missing opts Prop

### ISSUE THREAD

**Issue by maennchen** [msaraiva/surface#220]
The prop `opts` has been removed from `Select`. (#215)

It does not offer an alternative for all needed other options like `disabled`.

**Comment by maennchen** [comment]
https://github.com/msaraiva/surface/issues/200#issuecomment-727577086

This is not enough because of that part of the select docs:

> All other options are forwarded to the underlying HTML tag.

**Comment by msaraiva** [comment]
@maennchen you absolutely right. It shouldn't have been removed. I missed that in the review. We need to add it back.

Thanks for reporting the issue.
