### ISSUE TITLE
Add id and name props to all form components

### ISSUE THREAD

**Issue by Malian** [msaraiva/surface#226]
See discussion in #222 and [this](https://github.com/msaraiva/surface/pull/222#discussion_r535200846) discussion.

> I will check if every form components can handle id and name.

I'm quite confident that they should since they all use the same underlying functions like `generic_input/4`, `select/4` and `datetime_builder/5`.

> In the meantime, I suggest to put the "opts" back into date, time and datetime component mentioned above and make a separate merge request to implement the `id` and `name` in all the form components.

Yeah, I believe we should keep `opts` even if we add `id` and `name`. This way we keep the component more flexible regarding future changes in the underlying functions. So, yes. I think you can keep `opts` and then later add `id` and `name` to all components.

_Originally posted by @msaraiva in https://github.com/msaraiva/surface/pull/222#r535454291_

**Comment by Malian** [comment]
@msaraiva  After few investigations, the `name` props will not be an issue. However, the `id` props makes the component stateful.

The doc says: 
> A stateful component is a component that receives an :id on live_component/3

I am not sure we could easily add an `id` props to all form component and keep them stateless.

**Comment by msaraiva** [comment]
You're right. We'll need to change the way the property `id` of a `Surface.Component` is passed to the `live_component`. I'll take a look at it and let you know what I can do before we move on.

**Comment by msaraiva** [comment]
> I am not sure we could easily add an `id` props to all form component and keep them stateless.

@Malian after #227 is merged, we can! 😉

**Comment by msaraiva** [comment]
@Malian #227 has been merged. Please let me know if you run into any issue.
