### ISSUE TITLE
Eex translation issue with `inputs_for`

### ISSUE THREAD

**Issue by neilberkman** [msaraiva/surface#23]
This could be a problem on our end but we're stumped. We're getting this warning:

>` warning: unexpected beginning of EEx tag "<%=" on end of expression "<%= end %>", please remove "=" accordingly` [reference to `{{ end }}` line below]

with code like the following:

```elixir
 def render(assigns) do
    ~H"""
    {{form = form_for @changeset, Routes.user_path(@socket, :create), [phx_change: "update", class: "form"] }}
          {{ inputs_for form, :emails, fn fp -> }}
            {{ email_input fp, :address }}
          {{ end }}
    <#Raw></form></#Raw>
    """
  end
```

Could this be an issue with the Eex translator? I'm able to reproduce this with current master.

**Comment by msaraiva** [comment]
Hi @neilberkman!

Just like React, Surface only accept complete/valid expressions inside `{{ ... }}`. A few exceptions are when used as attributes values to enable some extra syntactic sugar. Interpolation with partial expressions like `{{ inputs_for form, :emails, fn fp -> }}` cannot be handled. Ideally, in the near future, Surface will ship with wrapper components for every built-in form helper like `form` and `inputs_for`. Until then, we have a few options:

1. Move `form` and `inputs_for` up, outside the `~H`. Something like:

    ```elixir
    def render(assigns) do
      form = form_for assigns.changeset, Routes.user_path(assigns.socket, :create), [phx_change: "update", class: "form"]
      inputs = 
        inputs_for form, :emails, fn fp ->
          email_input fp, :address
        end

      ~H"""
      {{ form }}
        {{ inputs }}
      <#Raw></form></#Raw>
      """
    end
    ```
2. Wrap `inputs_for` in a function:

    ```elixir
    def render(assigns) do
      ~H"""
      {{ form = form_for @changeset, Routes.user_path(@socket, :create), [phx_change: "update", class: "form"] }}
        {{ inputs(form) }}
      <#Raw></form></#Raw>
      """
    end

    defp inputs(form) do
      inputs_for form, :emails, fn fp ->
        email_input fp, :address
      end    
    end
    ```
3. Use `~L` instead of `~H`:

    ```elixir
    def render(assigns) do
      ~L"""
      <%= form = form_for @changeset, Routes.user_path(@socket, :create), [phx_change: "update", class: "form"] %>
        <%= inputs_for form, :emails, fn fp -> %>
          <%= email_input fp, :address %>
        <% end %>
      </form>
      """
    end
    ```

Since you're not using, for this case, any of the enhancements offered by `~H`, I would probably stick with #&#8203;3 and just use `~L` 😉

**Comment by neilberkman** [comment]
Got it, thanks for much for your help!

**Comment by brainlid** [comment]
@msaraiva I hit a snag where I also wanted to handle `embeds_one` inputs using Surface. This led me to `inputs_for`, but the Phoenix Form helper really isn't written to work well with Surface. Ideally, I could do something like:

```elixir
<Form ...>
  <InputsFor for="emails">
    <FieldInput field="name">
      <TextInput />
    </FieldInput>
  </InputsFor>
</Form>
```
Where the InputsFor would setup the context. Then a field could check for an `:inputs_for` on the context or fallback to a `:form`. Without changes to Phoenix that won't work.

Just wondering if you have given more thought to a good way to solve this? My workaround is that in this special case, just don't use Surface and explicitly build the form layout without my other helpers.

**Comment by msaraiva** [comment]
@brainlid as far as I could see the way `inputs_for` is implemented today will not work well with contexts. As soon as I merge the new [context API](https://github.com/msaraiva/surface/issues/29), I'll start working on alternatives. I believe Surface should have built-in wrapper components around all those form helpers that are context friendly. I'll open an issue for it.

**Comment by msaraiva** [comment]
I'm closing this in favour of https://github.com/msaraiva/surface/issues/32
