### ISSUE TITLE
i18n/gettext - components

### ISSUE THREAD

**Issue by DamienFF** [msaraiva/surface#232]
Hi,
Thanks a lot for the library.
I am looking forward to using it in my next project.

I was wondering how to make i18n/gettext and components fit nicely together.

Let's consider a menu, for example, with items being components.
The items will probably be generated from a list or taken from the database.
To what I understood, gettext cannot be applied in this case.

I checked View I18n, and the internationalization is provided in the view itself (a map with a key per language).

Is there something planned in surface for these types of cases?
If not, what would be the recommended way?

Thanks in advance

**Comment by devilcoders** [comment]
I think the process is not different to the way, that of the one for the regular views. You just wrap your text with `gettext` function and translate it inside `.po` files.

**Comment by msaraiva** [comment]
I agree with @devilcoders. I don't think you have to do anything specific to make it work with Surface. It should work just like with any Phoenix view.
