### ISSUE TITLE
Make declaring slots mandatory

### ISSUE THREAD

**Issue by msaraiva** [msaraiva/surface#236]
Make declaring slots mandatory, even for `default` as proposed here https://github.com/msaraiva/surface/pull/208#discussion_r526865090.

Related code:

https://github.com/msaraiva/surface/blob/f373b0fbd193e9e60c95cbc42354e56346b031b6/lib/surface/compiler.ex#L661

and

https://github.com/msaraiva/surface/blob/f373b0fbd193e9e60c95cbc42354e56346b031b6/lib/surface/api.ex#L170-L175

There might be other places where conditionals like `slot_name != :default` have been used. We'll probably need to remove them too.

**Comment by Malian** [comment]
@msaraiva I'll tackle this.

I am wondering if we should keep the short syntax of slot for default: `<slot />` or should we force `<slot name="default" />`? I am in favor to allow the short syntax as it often happens to write this code.

**Comment by msaraiva** [comment]
> I am wondering if we should keep the short syntax of slot for default: `<slot />`

Yes. Let's keep it.

> by mandatory, you mean we should raise a compiler error or a keep warnings?

I think it should be an error. 

If the use tries something like:

```
<slot name="heade"/>
```

We have two situations, which each of them could have slightly different messages, if case we want to give a more assertive message.

### 1. There are slots defined

```
no slot "heade" defined in the component 'MyProject.MyComponent'

Did you mean "header"\?

Declared slots: "default", "footer" and "header"
```

### 2. There's no slot defined

```
no slot "heade" defined in the component 'MyProject.MyComponent'

Hint: You can define slots using the `slot` macro.

For instance: `slot heade`
```

WDYT?

**Comment by msaraiva** [comment]
@Malian we could also keep it as a warning for now and maybe turn it into a error only when we release `v0.2.0`. This way we make sure we don't break any project now. WDYT?

If you agree, then we'll have to keep automatically including the `used_slots` to the list of slots here:

https://github.com/msaraiva/surface/blob/f373b0fbd193e9e60c95cbc42354e56346b031b6/lib/surface/api.ex#L170-L175

**Comment by lnr0626** [comment]
If we're keeping the short syntax for the default slot (which i do agree with), we may want to add another message for when a user uses `<slot />` but hasn't defined the default slot (something like `The default slot must be declared before it can be used via <slot />`?) - just as a reminder of that short hand convention

**Comment by msaraiva** [comment]
I agree. I think this should be enough:

### 3. Using default's slot short syntax (no name)

```
no default slot defined in component 'MyProject.MyComponent'

Please declare the default slot using `slot default` in order to use the `<slot/>` notation.
```

**Comment by Malian** [comment]
I am torn between the two proposals.

On the one hand, the advantage of warnings is that you can update your project little by little and not have to fix everything at once. The disadvantage is that we'll have to rework on this point before the 2.0.0 release.

On the other hand, the update is straightforward.

Finally, I am in favour of keeping the warnings for the following reasons:

- Most of the CI system runs compile with the `--warnings-as-errors` flag, so I suppose developers will have to update their code anyway.
- It will let us some time to write proper documentation
- Better DX experience

**Comment by Malian** [comment]
> If you agree, then we'll have to keep automatically including the `used_slots` to the list of slots here:
> 
> https://github.com/msaraiva/surface/blob/f373b0fbd193e9e60c95cbc42354e56346b031b6/lib/surface/api.ex#L170-L175

I am not sure we need to keep references to `used_slot`. In my tests I removed all the references and the tests continue to be green with some new warnings as expected. Could you explain me why we need to keep it as `get_slots` is part of the private api?

**Comment by msaraiva** [comment]
> Could you explain me why we need to keep it as `get_slots` is part of the private api?

These functions:

https://github.com/msaraiva/surface/blob/f373b0fbd193e9e60c95cbc42354e56346b031b6/lib/surface.ex#L273

and

https://github.com/msaraiva/surface/blob/f373b0fbd193e9e60c95cbc42354e56346b031b6/lib/surface/directive/slot_props.ex#L31

depend on the full list in order to make their validations. No matter if the slot was declared or auto-declared using the `<slot>` tag. If we decide to show a warning but keep everything working, we need to keep the auto-declaration, otherwise, we may see multiple warnings that might be misleading to the user on how the problem should be addressed. I believe we missed some tests to cover those scenarios. 

The major disadvantage of showing a warning instead of raising an error here is that since warnings doesn't halt the execution, they might cascade and we have to worry about all other places that might also show warnings or even errors, not for the expected reasons but because they received inconsistent inputs.

The question is: can we guarantee the code runs consistently if we add just a warning? I believe we can but it will require more conditionals along the way to avoid multiples misleading warnings. So maybe the best decision would be to raise an error and just don't care about auto-declaring anything.
