### ISSUE TITLE
Fix line offset when using single-line ~H variants

### ISSUE THREAD

**Issue by msaraiva** [msaraiva/surface#240]
Before Elixir `v1.10` we were not able to report the error line correctly for single-line `~H` because there was no way to retrieve the information about the delimiter so we had to add a `+ 1` to the line offset because using `~H"""` is more common than using the other single-line variants like `~H"..."` and `~H(...)`. See:

https://github.com/msaraiva/surface/blob/2286f8b6130679f60fd5ece18251d3f84a1dd830/lib/surface.ex#L106-L109

Since `v1.10`, the delimiter is available so we're now able to fix this. Here's the difference:

### ~H""" in Elixir `v1.9.1`

```elixir
{:sigil_H, [], [{:<<>>, [], ["text\n"]}, []]} 
```

### ~H() in Elixir `v1.9.1`

```elixir
{:sigil_H, [], [{:<<>>, [], ["text"]}, []]}
```

### ~H""" in Elixir `v1.11.1`

```elixir
{:sigil_H, [delimiter: "\"\"\""], [{:<<>>, [indentation: 2], ["text\n"]}, []]}
```

### ~H() in Elixir `v1.11.1`

```elixir
{:sigil_H, [delimiter: "("], [{:<<>>, [], ["text"]}, []]}
```

**Comment by Malian** [comment]
@msaraiva I do not understand how the delimiter is available inside the sigil macro. It's seems that the only difference is that the `identation` key is available when `"""` is used. Would you want to modify the line_offset based on the presence of that key?

**Comment by msaraiva** [comment]
@Malian you're right. Only `:indentation` is available inside the macro and it's only added from `v1.11` on. So, in theory, we should not add `+ 1` to the offset if version >= 1.11 and the `:indentation` key is not present (it should only be present if we're using `~H"""`).
