### ISSUE TITLE
Error with TextInput on surface-demo / getting started

### ISSUE THREAD

**Issue by rubysolo** [msaraiva/surface#25]
Thanks for your work on this, it looks *amazing*!

I'm experimenting with Surface on a project, and I ran into an issue with the example `TextInput` component on http://surface-demo.msaraiva.io/getting_started.  With the code as is, I get the error:

```
[error] GenServer #PID<0.1207.0> terminating
** (RuntimeError) expected TextInput.render/1 to return a %Phoenix.LiveView.Rendered{} struct

Ensure your render function uses ~L, or your eex template uses the .leex extension.
```

I was able to work around it by wrapping the phoenix form `text_input` call with an H-sigil like:

```
~H"""
{{ text_input(...) }}
"""
```

I'm not sure if this is the best solution, and I did not see the repo for the demo site.  If  this is a good fix, I'd be happy to submit a PR if that repo is public.

Thanks!

**Comment by msaraiva** [comment]
Hi @rubysolo!

This is the right fix! In case you're curious, I explained the reason [here](https://github.com/msaraiva/surface/issues/10#issuecomment-574843906). I'll leave this issue open until I update the demo. There are other changes in the API that will be merged in the next couple of days that will require updating some of the examples as well.
