### ISSUE TITLE
Checkbox nested within Label in form does not work

### ISSUE THREAD

**Issue by lnr0626** [msaraiva/surface#250]
I'm converting an older live view over to use surface that has a form with a checkbox input like so:

```
<div class="...">
  <%= label f, :field do %>
    <%= checkbox f, :field %> The Label
  <% end %>
</div>
```

I switched it to:
```
<Field name="field" class="..." >
  <Label>
    <Checkbox /> The Label
  </Label>
</Field>
```

Which compiles fine, but fails to render with `cannot convert component Surface.Components.Form.Checkbox with id nil to HTML.`

As I'm writing this, I'm realizing part of the issue is because of an underlying issue with live view - as we're passing this data into the label function, rendering components within the label template doesn't actually work. I was able to work around this by using the field prop, and then just calling the underlying checkbox function directly:

```
<Field name="field" class="..." >
  <Label>
    {{ checkbox f, :field }} The Label
  </Label>
</Field>
```

We should probably add a warning to the Label docs to indicate this shortcoming

**Comment by msaraiva** [comment]
Hey @lnr0626! I'm back :)

Yeah. It's a LV limitation. The real issue is that `label/3` uses `content_tag/3` under the hood. Anything using `content_tag/3` cannot call `live_component`. I'm sure the Phoenix core team will eventually address this issue in the future but until then, maybe we should consider implementing our own `<Label>` without depending on `label/3`. We did this already for `<LivePatch>` and `<LiveRedirect>`. WDYT?

**Comment by lnr0626** [comment]
That makes sense - we should be able to do that transparently to users and just update the `Label` component if/when the core team addresses the limitation.

Are there any other form components that would make sense for? I haven't run into any others that have caused issues

**Comment by msaraiva** [comment]
> Are there any other form components that would make sense for?

I don't think so. This is only an issue for components that have slots that may accept live components in their content. Aside from  `Label`, only `Field` and `FieldContext` requires that but they're already content_tag-free.

I believe none of the form inputs requires that. One exception, which is not related to forms, is the `<Link>` component. It uses `link/3`, which uses `content_tag` under the hood.

So my guess is that we have only `Label` and `Link` in that situation in the core library.

@miguel-s and @Malian can you think of any other component that might present this isssue?

**Comment by miguel-s** [comment]
`Label` and `Link` are the only two components I've had issues with in my own code.

Also did a quick review of other components and couldn't find any that require a refactor.

**Comment by msaraiva** [comment]
Closing this in favour of #262
