### ISSUE TITLE
aliasing does not work

### ISSUE THREAD

**Issue by olivermt** [msaraiva/surface#251]
I have a file lib/collector_web/live/page_live_surface.ex 

with contents:
```
defmodule CollectorWeb.PageLiveSurface do
  # alias CollectorWeb.Component.Base.NavBar
  use Surface.LiveView

  def mount(socket) do
    socket = Surface.init(socket)
    {:ok, socket}
  end

  def render(assigns) do
    ~H"""
    <CollectorWeb.Component.Base.NavBar />
    """
  end
end

```
The NavBar is in lib/collector_web/components/base/navbar.ex.

If I alias (the commented line at the top) and do `<NavBar />` it says it cant find module.

If I use the fully qualified module name it works just fine.

**Comment by dvic** [comment]
That should work right? Not sure how the Surface.LiveView macro works but did you try placing it after the `use` statement?

**Comment by olivermt** [comment]
indeed it was a problem of aliasing BEFORE the use, I didn't know the order counted.. :)
