### ISSUE TITLE
`@myself` property incorrectly generates warning

### ISSUE THREAD

**Issue by derekkraan** [msaraiva/surface#252]
I believe this is a bug in Surface. When I use the `@myself` assign in a (stateful) component, I get the following warning:

![image](https://user-images.githubusercontent.com/522157/104454968-ec296500-55a6-11eb-899f-48dcb0799fdd.png)

We run `mix compile --warnings-as-errors` in our CI (as many do, I believe), which means that this is breaking for our build.

I should note that using `@myself` in the template works just fine, despite this error, and following the suggestion contained in this error, adding `prop myself, :any`, results in `@myself` being empty, with the consequence that events from tags like `<button phx-click="event_name" phx-target={{ @myself }}>Button</button>` end up going to the parent live view and not to the surface component like they are supposed to.

**Comment by derekkraan** [comment]
Actually looking at the code, I believe this has already been fixed in `master`. Any chance we could get a new release?

**Comment by msaraiva** [comment]
Hi @derekkraan!

Version `v0.1.2` should be released this week.
