### ISSUE TITLE
is there a way to use Inputs with changeset?

### ISSUE THREAD

**Issue by Bogdan1001** [msaraiva/surface#253]
Hello,

When I trying to use Inputs with :atom key it's works fine.

```
    <Form for={{ :parent }} change="field_change" submit="save">
    <Inputs for={{ :child }} :let={{ form: f }}>
    {{text_input(assigns, f, "First Name", @user.first_name)}}
    </Inputs>
    </Form>
```

But when I adding @changeset there I get an error.
```
    <Form for={{ :@changeset }} change="field_change" submit="save">
    <Inputs for={{ :first_name }} :let={{ form: f }}>
    {{text_input(assigns, f, "First Name", @user.first_name)}}
    </Inputs>
    </Form>
```

> could not generate inputs for :first_name from MyApp.Module. Check the field exists and it is one of embeds_one, embeds_many, has_one, has_many, belongs_to or many_to_many

**Comment by olivermt** [comment]
Could you show the complete code? It sounds like its not a changeset you're passing to @changeset

**Comment by joshuataylor** [comment]
Can you try `for={{ @changeset }}`

**Comment by miguel-s** [comment]
Seems like you have a typo in the changeset version here `for={{ :@changeset }}`.

As already mentioned by @joshuataylor try replacing `:@changeset` with `@changeset` (remove the colon before the @).

**Comment by Bogdan1001** [comment]
> Seems like you have a typo in the changeset version here `for={{ :@changeset }}`.
> 
> As already mentioned by @joshuataylor try replacing `:@changeset` with `@changeset` (remove the colon before the @).

Hi thank you for replies,
Sorry for the typo I think I did it only when edit the code here in the issue.
Anyway I did check @changeset without colon and still get the error

could not generate inputs for :first_name from MyApp.Module. Check the field exists and it is one of embeds_one, embeds_many, has_one, has_many, belongs_to or many_to_many

**Comment by lnr0626** [comment]
is `first_name` an embed or association? or just a string? `Inputs` is a wrapper around `inputs_for`, and so can only be used with fields that are either an embed or association (`embeds_one, embeds_many, has_one, has_many, belongs_to or many_to_many`)

For a string field:
```
<Form for={{ @changeset }} change="field_change" submit="save">
   <Field name="first_name">
     <Label />
     <TextInput />
   </Field>
</Form>
```

should work (you can use `FieldContext` if you don't want the wrapping div). If you have common styling you want for labels/inputs/etc. you can create your own components that wrap the various surface form components.

The only field that you'd need to provide a value for when you're using changesets is a password input as live view resets the password input for security reasons (https://hexdocs.pm/phoenix_live_view/form-bindings.html#password-inputs)
