### ISSUE TITLE
do you have any plan to support PWA?

### ISSUE THREAD

**Issue by mrchypark** [msaraiva/surface#256]
It can be a naive and stupid question.

Could liveview or surface support PWA?

**Comment by harmon25** [comment]
All you need for a PWA is to statically serve a [web app manifest](https://web.dev/add-manifest/)

In the context of liveview + surface, it would be possible, but likely require an [offline fallback page](https://web.dev/offline-fallback-page/),  live_view is pretty dependent on the network.
If you want offline support or client stored/cached data - would probably be better off with full blown SPA.

**Comment by mrchypark** [comment]
@harmon25 

thank you for reply. 

The front-end continues to be varied and varied. I hope that the surface will also show its strengths in the change. As a user who doesn't want to use js, I am looking at surface with interest. I understand that it depends on the network as a design limitation. However, it is a difficult choice for me, considering pwa as an alternative to the app.

Recently react introduced server componant. https://addyosmani.com/blog/react-server-components/

There is a case of supporting pwa using WebAssembly like go-app. https://github.com/maxence-charriere/go-app

The current worries are the same to be done in liveview.

Thanks for answering.
