### ISSUE TITLE
README typo on where to external css?

### ISSUE THREAD

**Issue by zorn** [msaraiva/surface#257]
I saw this in the Getting Started, but is the file in question `lib/my_app_web/templates/layout/root.html.leex` ?

<img width="1122" alt="Screen Shot 2021-01-24 at 7 18 24 PM" src="https://user-images.githubusercontent.com/52168/105648371-187f9400-5e79-11eb-86e9-447a12aa0dfd.png">

**Comment by msaraiva** [comment]
Hi @zorn!

You're right. We have to update that. 

BTW, the source code for the website is now available at https://github.com/surface-ui/surface_site so feel free to open a PR in case you find any other issue.

Thanks!

**Comment by zorn** [comment]
Thanks. Appreciate have the documentation site open source. I'm sure that will help my own and others discovery paths.

**Comment by msaraiva** [comment]
Closing this in favour of https://github.com/surface-ui/surface_site/issues/4
