### ISSUE TITLE
Don't validate undefined assign outside `render/1`

### ISSUE THREAD

**Issue by msaraiva** [msaraiva/surface#261]
The following gives a `undefined assign `@message` warning:

```elixir
  defp message(assigns) do
    ~H"""
    <div>
      {{ @message }}
    </div>
    """
  end
```

The warning should appear only if the caller module is a Surface Component/Liveview and the caller function is `render/1`.

**Comment by Malian** [comment]
Hi @msaraiva I am not able to reproduce the bug. Could you give me a complete example. I'll be glad to tackle this bug.

**Comment by msaraiva** [comment]
Hi @Malian!

Here's a complete example:

```elixir
defmodule MyComponent do
  use Surface.Component

  def render(assigns) do
    ~H"""
    <div>
      {{ sum(assigns) }}
    </div>
    """
  end

  def sum(assigns) do
    ~H"""
    {{ @a + @b }}
    """
  end
end
```

You should see this:

![image](https://user-images.githubusercontent.com/457237/107028862-e9c4c000-678c-11eb-8a60-6b067a46d8a6.png)

As mentioned, this validation should happen only if the caller module is a Surface Component/LiveComponent/Liveview AND the caller function is `render/1`.

**Comment by msaraiva** [comment]
@Malian BTW, thanks for stepping in. I've been quite busy working on the Surface Catalogue for the last weeks. I appreciate the help with the pending issues. ❤️

**Comment by Malian** [comment]
@msaraiva I fixed the warning but I discovered a new one with LiveComponent:

```elixir
defmodule MyComponent do
  use Surface.LiveComponent

  def render(assigns) do
    ~H"""
    <div>
      {{ sum(assigns) }}
    </div>
    """
  end

  def sum(assigns) do
    ~H"""
    {{ @a + @b }}
    """
  end
end
```

![Screenshot from 2021-02-05 19-25-24](https://user-images.githubusercontent.com/553321/107073744-080bd980-67e8-11eb-8dfd-63bb9ef26399.png)

I suppose we also have to fix this?

**Comment by msaraiva** [comment]
Yeah, we need to fix that too :)
