### ISSUE TITLE
Allow <Link> and <Label> to accept components as children

### ISSUE THREAD

**Issue by msaraiva** [msaraiva/surface#262]
As reported in `#168` and `#250`, Phoenix's `link` and `label` functions depend on `content_tag`, i.e. they don't allow including components in their inner block. If you try to do that, you get  the following error:

```
** (exit) an exception was raised:
    ** (ArgumentError) cannot convert component Surface.Components.Form.Checkbox with id nil to HTML.
A component must always be returned directly as part of a LiveView template.
For example, this is not allowed:
    <%= content_tag :div do %>
      <%= live_component @socket, SomeComponent %>
    <% end %>
...
```

We should roll our own implementation without depending on `link` and `label` just like we did for `LivePatch` and `LiveRedirect`.

**Comment by miguel-s** [comment]
I could work on this over the weekend.

Does this issue depend on #255 being finished first?

**Comment by msaraiva** [comment]
Hi @miguel-s! 

Thanks for stepping in.

> Does this issue depend on #255 being finished first?

I don't think so as its implementation should be consistent with the other existing components like LivePatch and Liveview. When #255 is ready it will change the behaviour of all of them.
