### ISSUE TITLE
Render function not run when component declared as a "slot"

### ISSUE THREAD

**Issue by ewildgoose** [msaraiva/surface#265]
I wanted to make a card component with optional <Header> and <Footer> parts. So starting with the example in the docs we see that the wrapper HTML is always defined and the slot is included in the middle. 

The obvious solution seems to be to create Header/Footer components which will render the appropriate HTML. However, using pure components means that the user needs to know precisely how to insert them inside the Card component. slots seem to solve this

So I tried defining a component like this:

```
defmodule ExampleWeb.Component.Card.Footer do
  @moduledoc false

  use Surface.Component, slot: "footer"

  prop class, :css_class, required: false, default: "bg-gray-50 px-5 py-3 sm:px-5 text-lg text-gray-500"
  slot default

  def render(assigns) do
    ~H"""
      <div class={{ @class }}>
        <slot name="default"/>
      </div>
    """
  end
end
```

However, the action of declaring that it's a "slot:" seems to stop render being called when it's inserted into the component upstream?

So I would desire that

```
  <Card>
    stuff
    <Footer class="some classes">
      a footer
    </Footer>
  </Card>
```

Will both render the Footer component *and* insert it into the Card component where I use the given slot. This seems useful more widely as well I think? eg your Grid example could acquire a default render function for the Column?

However, the original use case was to have a component with an optional slot where the content of the slot is run through a template function, perhaps there is another way to handle this?

**Comment by msaraiva** [comment]
Hi @ewildgoose!

There's a similar issue here https://github.com/msaraiva/surface/issues/212 where we've discussed the reasons why slotable components are currently renderless and also presented some possible alternatives. We will probably create a separate type of component (maybe `Surface.Template`) to avoid confusion. Please let me know in case you need any extra information or have any suggestion.

**Comment by ewildgoose** [comment]
Hmm, ok, so I think I see why this is confusing. However, I think the confusion comes (to a new user like me) because we are both using the renderless component for config only in the case of the "Grid.Columns" example, but with content in the slot in the case of the Card example

Having experimented a little more, I'm still not sure that I see the issue? Apologies because I'm probably at least 2 steps behind you.

So sticking with the card example above, I notice that trying to define two "Footer" slots simply keeps the first one:
```
<Footer>
  First footer
</Footer>
<Footer>
  I never see this footer
</Footer>

...then render in the card component with 
  <slot name="footer"/>
```

So it *feels* to be in this case as though the Footer component is behaving both as a renderless and a render-full component.

My naive self doesn't understand why the content isn't run through the render/1 function of the component before it's snatched? Possibly with limits on the evaluation environment? In other words I'm kind of expecting it to behave like this:

```
<Footer>
  <Footer>
    I never see this footer
  </Footer>
</Footer>
```

There the outer component acts as a renderless component and the inner behaves like a normal component to render things?

The above design seems useful as simply emulating it by using an additional (redundant?) component shows how it would be implemented:

```
<Footer>
  <FooterFormatter class="fancy classes" options="whatever">
    I never see this footer
  </FooterFormatter>
</Footer>
```

It just seems to lead to extra typing to need to create a "FancyFooter" and "FancyFooterFormatter", etc?

I do apologise in advance since I'm almost certainly missing something the subtleties of why this is difficult. Thanks for humouring me.

**Comment by msaraiva** [comment]
Closing this in favours of https://github.com/msaraiva/surface/pull/283
