### ISSUE TITLE
Support colocated .js files for self-registrable/live-reloadable  hooks

### ISSUE THREAD

**Issue by msaraiva** [msaraiva/surface#269]
Hi folks!

Does anyone out there ever wondered if we could have a more intuitive way to define **JS hooks for components**?

Yesterday I finally had the change to put something together. 

What have I managed to do, so far?

  1. Automatically load component hooks exported by a colocated `.js` file
  2. Automatically namespace imported hooks to avoid conflicts
  3. Automatically register loaded hooks to the socket
  4. Safely import hooks defined by other components
  4. Support live reload for component hooks

What can we still do?

  1. Static checking for missing hook files
  2. Static checking for unused hook files
  3. Static checking for undefined hooks in a file

As I'm still playing with it, I'd love to hear your thoughts on the idea, especially about limitations. I'm sure we'll not be able to cover all cases but I tested this approach with all components I had that require custom JS and it worked perfectly!

Here's the branch if you want to try it out https://github.com/msaraiva/surface/tree/ms-component-assets

## Setup

Update `mix.exs` to point to the branch above and set up the Surface compiler:

```elixir
defp deps do
  [
    ...,
    {:surface, git: "git@github.com:msaraiva/surface.git", branch: "ms-component-assets", override: true}
  ]
end

def project do
  [
    ...,
    compilers: [:surface, :phoenix] ++ Mix.compilers()
  ]
end
```

Update `.gitignore`:

```
# Ignore auto-generated hook files
/assets/js/hooks/
```

Update `assets/js/app.js`:

```js
import hooks from "./hooks"

// You can merge it with other non-surface hooks, if you need
let Hooks = {...hooks}
```

Update the Endpoint options in `config/dev.exs` for live reload of JS hooks:

```elixir
config :my_app, MyAppWeb.Endpoint,
  ...
  reloadable_compilers: [:phoenix, :elixir, :surface],
  live_reload: [
    patterns: [
      ~r"lib/my_app_web/(live|components)/.*(ex|js)$",
      ...
    ]
```

## Usage

Create a colocated `.js` file with the same base name of the component.

Example:

```
card.ex
card.js
```

Export the hooks you need in `card.js`:

```js
let Card = {
  mounted(){
    console.log("Card mounted")
  }
};

let OtherHook = {
  mounted(){
    console.log("OtherHook mounted")
  }
};

export {Card, OtherHook};
```

Use the `:hook` directive to bind whatever hook you need:

```vue
<div :hook="Card">
  ...
</div>
```

You can also access hooks defined by other components using option `:from`:

```vue
<div :hook={{ "Card", from: MyComponents.CardList }}>
  ...
</div>
```

That should be all! 

Let me know if you run into any issue. I want to have as much feedback as possible to make sure the idea is solid before moving on with this.

Cheers.

**Comment by harmon25** [comment]
Works great!
Only suggestion is a different default output directory other than `assets/js/hooks` .
Some suggestions: `assets/js/surface-hooks` , `assets/js/surface` 

OR prefix with an underscore to make it obvious you should not be manually adding files or touching that directory:  `assets/js/_hooks`

**Comment by msaraiva** [comment]
@harmon25 thanks for the suggestion. I'll change that. In the meantime, if you need the compiler to generate the files in another folder, you can set the `hooks_output_dir` option in your config. 

Example:

```elixir
config :surface, :compiler, hooks_output_dir: "assets/js/surface"
```

**Comment by msaraiva** [comment]
@harmon25 I'm changing the default output folder to `assets/js/_hooks`. 

Another thing I'm planning to change is to use `.hooks.js` instead of `.js` to make it explicit that we're considering anything exported as hooks so they will be passed to the socket as such. So we'd have:

```
card.ex
card.hooks.js
```

WDYT?

**Comment by harmon25** [comment]
I like it, a more explicit default is a good idea!

**Comment by olivermt** [comment]
I think we should revisit this @msaraiva because I think you forgot the main feature we discussed when we specced up this, to grab hooks from dependencies. Currently the compiler does not scan the deps for hooks, which makes it a bit clunky to use stuff like my bootstrap lib as a dep, as you'd have to import them in a very specific way to match the auto-generated hooks.

**Comment by olivermt** [comment]
After more finagling I can say for sure we *have* to have this feature for this to be used in a sensible manner.
Since Surface copies over the files, importing from node modules will always be off if you dont copy the files over.
That means that to use my lib I have to:
1. Copy over the files manually
2. Import them as such `import { Modal } from "./hooks/modal";`
3. Namespace them since I use `:hook` like this manually:
```
const hooks = {
  "SurfaceBootstrap.DropDown#DropDown": DropDown,
  "SurfaceBootstrap.Modal#Modal": Modal
};
```
I think this can be solved very gracefully with a simple config option like `surface: hook_deps: ["surface_boostrap", "whatever_else_lib"]` and you scan and copy from there as well.
