### ISSUE TITLE
<Link> no longer accepts "link with scheme"?

### ISSUE THREAD

**Issue by neilberkman** [msaraiva/surface#272]
After upgrading to 0.3.0 a number of tests in my application started failing due to `<Link>` tags with `to` attributes with tuples of the form `{:scheme, :link}`. `Phoenix.HTML.Link` accepts this format:

https://github.com/phoenixframework/phoenix_html/blob/2d09867665295ac124b8b4913f14b6b80b0cb952/test/phoenix_html/link_test.exs#L56-L57

I'm using it for "deep links" to apps on mobile.

**Comment by msaraiva** [comment]
@miguel-s I believe we'll need to partially copy this `valid_destination!` implementation out of the `link`code. Correct?

https://github.com/phoenixframework/phoenix_html/blob/2d09867665295ac124b8b4913f14b6b80b0cb952/lib/phoenix_html/link.ex#L147

**Comment by miguel-s** [comment]
Thanks for pointing me to the relevant places in the Phoenix codebase @neilberkman @msaraiva.

PR #273 should fix this particular issue, but I'll check if we missed anything else to keep feature parity with Phoenix.

**Comment by msaraiva** [comment]
Hey @miguel-s! That was fast :)

Thank you! ❤️

**Comment by msaraiva** [comment]
@neilberkman thanks for reporting this issue.
