### ISSUE TITLE
ErrorTag problem with unsafe_unique changeset validation error

### ISSUE THREAD

**Issue by hok** [msaraiva/surface#276]
It looks like the ErrorTag component doesn't handle the case of receiving a changeset that contains a validation error for uniqueness validation. In this case, the validations fields value is a list and not a value that can be converted to a string.

```
errors: [
    email: {"has already been taken",
     [validation: :unsafe_unique, fields: [:email]]}
  ]
```

The error is the following:

```
** (ArgumentError) cannot convert the given list to a string.

To be converted to a string, a list must either be empty or only
contain the following elements:

  * strings
  * integers representing Unicode code points
  * a list containing one of these three elements

Please check the given list or call inspect/1 to get the list representation, got:

[:email]

    (elixir 1.11.3) lib/list.ex:925: List.to_string/1
    (surface 0.3.0) lib/surface/components/form/error_tag.ex:127: anonymous fn/2 in Surface.Components.Form.ErrorTag.translate_error/1
    (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
    (surface 0.3.0) lib/surface/components/form/error_tag.ex:112: anonymous fn/7 in Surface.Components.Form.ErrorTag.render/1
    (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
    (surface 0.3.0) lib/surface/components/form/error_tag.ex:109: anonymous fn/6 in Surface.Components.Form.ErrorTag.render/1
    (phoenix_live_view 0.15.4) lib/phoenix_live_view/diff.ex:342: Phoenix.LiveView.Diff.traverse/6
    (phoenix_live_view 0.15.4) lib/phoenix_live_view/diff.ex:430: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/6
```

**Comment by Malian** [comment]
Hello @hok ! Thanks you for reporting this.

When using the Surface ErrorTag component, you have to specify a translator in the `Surface` config. The documentation of the `Surface.Components.Form.ErrorTag` module says:

> When using Gettext, you can use configuration to route all errors through the `MyAppWeb.ErrorHelpers.translate_error/1` function generated by Phoenix, which utilizes `Gettext`. You need to provide a tuple with the module and the name of the function (as an atom) as follows

  ```elixir
  config :surface, :components, [
    {Surface.Components.Form.ErrorTag, default_translator: {MyAppWeb.ErrorHelpers, :translate_error}}
  ]
  ```

Does it fix your issue?

@msaraiva I believe we should add a section about this in the [Getting Started guide](http://surface-demo.msaraiva.io/getting_started). Could we also return a better error like: "Hint: Have you configured Surface to use Phoenix ErrorHelper?"

**Comment by hok** [comment]
I did configure it but it looks like the code never reaches my ErrorHelpers module. I'll double-check that I didn't miss anything.

**Comment by hok** [comment]
@Malian oh, it does work after using your suggestion. I needed to change `translator` to `default_translator`.

The documentation here http://surface-demo.msaraiva.io/builtincomponents/ErrorTag specifies `translator` and not `default_translator`:

```elixir
config :surface, :components, [
  {Surface.Components.Form.ErrorTag, translator: {MyAppWeb.ErrorHelpers, :translate_error}}
]
```

**Comment by Malian** [comment]
Indeed, the Surface website is outdated. We have to upgrade the Surface dependency to the latest version. Thanks for catching this.

**Comment by Malian** [comment]
@hok The [surface website](http://surface-ui.org/) has been updated!
