### ISSUE TITLE
Warn if prop is required and has default value

### ISSUE THREAD

**Issue by colinsmetz** [msaraiva/surface#281]
Reading the documentation, I was surprised that several examples show a `prop` that is `required` AND has a default value. The example in the README, for example, shows:

```elixir
prop name, :string, required: true, default: ""
```

This feels strange to me: what is the point of providing a default value if the prop **must** be defined anyway?

On the other hand, it seems pretty happy with a `prop` that is **not** required but has no default. In that case it seems the default "default" is `nil`, which makes sense but I haven't seen it mentioned in the doc.

My impression is that both options are antagonist. I would expect to have a warning when:
- `required` is `true` and there is a default ("default value will always be ignored")
- `required` is `false` and there is no default

What do you think? Did I miss something?

**Comment by Malian** [comment]
Thanks @colinsmetz for your feedback.

I agree that it feels strange to have a default value with a required prop. By saying the prop is required you expect the user to always provide a value, so making it have a default value defeats the purpose of the prop being required. As you suggested, a simple warning is enough to inform the user. We also have to update the doc accordingly.

I'm not sure that issuing a warning when the prop is not required and no default value has been set is a good idea. What about a truly optional prop? Imagine a `Fullname` component with two props, `firstname` and `lastname` where neither `firstname` nor `lastname` are required. What could be the default value in that case?

I am afraid that if we emit a warning, the user will have to modify his code like below and I do not see the real value from a DX:
```diff
- prop name, :string
+ prop name, :string, default: nil
```

This is also linked to #270

**Comment by msaraiva** [comment]
Hi @colinsmetz!

We should update definitely update the docs. I believe you found this one here I believe this the one at http://surface-demo.msaraiva.io/properties, right?

@Malian I think we could just emit a warning like:

```
warning: setting a default value on a required prop has no effect. Either set the default value or set the prop as required.
```

**Comment by colinsmetz** [comment]
> I'm not sure that issuing a warning when the prop is not required and no default value has been set is a good idea. What about a truly optional prop? Imagine a Fullname component with two props, firstname and lastname where neither firstname nor lastname are required. What could be the default value in that case?

Indeed, after more thinking it makes sense.

> We should definitely update the docs. I believe you found this one here http://surface-demo.msaraiva.io/properties, right?

Yes! It's also the example that is used [in the README](https://github.com/msaraiva/surface#example), so the first bit of Surface I saw.

**Comment by Malian** [comment]
@colinsmetz your suggestion has been merged into master.
