### ISSUE TITLE
Getting started guide

### ISSUE THREAD

**Issue by rmayhue** [msaraiva/surface#285]
I've been interested in Surface for a while now and with the new changes in the latest release I've decided to get my feet wet and use it for a new project. The question I have is this: Is the [Getting Started](http://surface-demo.msaraiva.io/getting_started) guide (and other docs) up to date?

I noticed that the deps version is `{:surface, "~> 0.1.0"}` and the version listed in the page footer is **Surface** _v0.1.0_

Thanks!

**Comment by msaraiva** [comment]
Hi @rmayhue!

> Is the [Getting Started](http://surface-demo.msaraiva.io/getting_started) guide (and other docs) up to date?

No. They are not. But they will be in a few hours :)

**Comment by rmayhue** [comment]
Great! Thank you! :+1: 

And thank you for all of your hard work on Surface! It is very appreciated!

**Comment by msaraiva** [comment]
Hey @rmayhue!

The updated version is available at https://surface-site.gigalixirapp.com/. I still need to set up the new domain. Until then, feel free to use that access.
