### ISSUE TITLE
Add directive :show

### ISSUE THREAD

**Issue by msaraiva** [msaraiva/surface#31]
Similar to `:if` but the component will always be rendered and remain in the DOM, even when it's `false` (it just sets `display: none`)

**Comment by mazz-seven** [comment]
What about solving this with classes or inline styles?
I think it's better to keep the directives count to a minimum.

**Comment by msaraiva** [comment]
Hi @mazz-seven!

I agree we should keep the directives count to a minimum, however, the `:show` directive seems to be extremely useful in Surface especially because `:if` cannot be used along with `:for` in the same node (btw, I have a TODO to add a static check for this). If you want to conditionally show a component/tag, currently you need to either create an extra node or add a filter in the `for` comprehension.  Vue.js also has a `v-show` directive and I'm not aware of any problem in the community regarding its use. Since we're kind of mapping most of the Vue behaviours in our directives, it sounds like a good addition.  

And just for the record, I have only one more directive to be added before the first release, which is a `:phx-value` which will accept a keyword list or a map. So instead of being forced to pass values as separated attributes like: 

```
phx-value-myvar1="value1" phx-value-myvar2="value2" phx-value-myvar3="value3"
```

we can use:

```
:phx-value={{myvar1: "value1", myvar2: "value2", myvar3="value3"}}
```

or

```
values = %{,,,}
...
:phx-value={{values}}
```

Since `:show` is already on master, I'll close this issue but feel free to move on with the discussion in case you have other strong arguments against it ;)

**Comment by mazz-seven** [comment]
The Phoenix value directive is an absolutely going to improve our life. 

Regarding, the :show directive, I don't have anything against it. I'm a havy user of Reactjs so we don't really have any directives in it. 
I only remember the time with Angular 1, that have a confusing amount of directive. 
So, what I'm trying to say is, we should think really hard about adding directives. They are easy to add but almost impossible to remove. ;)

**Comment by msaraiva** [comment]
> we should think really hard about adding directives. They are easy to add but almost impossible to remove. ;)

Wise words 🙂
