### ISSUE TITLE
Add built-in form components

### ISSUE THREAD

**Issue by msaraiva** [msaraiva/surface#32]
Create built-in context friendly form components around Phoenix helpers.  

### List of Phoenix built-in form helpers

- [x] color_input (thanks to @alexandrubagu)
- [x] date_input (thanks to @alexandrubagu)
- [x] date_select (thanks to @alexandrubagu)
- [x] datetime_local_input (thanks to @alexandrubagu)
- [x] email_input (thanks to @alexandrubagu)
- [x] form_for (thanks to @zamith)
- [x] hidden_input (thanks to @alexandrubagu)
- [x] label
- [x] number_input (thanks to @alexandrubagu)
- [x] password_input (thanks to @alexandrubagu)
- [x] radio_button (thanks to @alexandrubagu)
- [x] range_input (thanks to @alexandrubagu)
- [x] reset (thanks to @alexandrubagu)
- [x] search_input (thanks to @alexandrubagu)
- [x] submit (thanks to @zamith)
- [x] telephone_input (thanks to @alexandrubagu)
- [x] text_input (thanks to @zamith)
- [x] textarea (thanks to @alexandrubagu)
- [x] time_input (thanks to @alexandrubagu)
- [x] url_input (thanks to @alexandrubagu)
- [x] checkbox (thanks to @miguel-s)
- [x] select (thanks to @miguel-s)
- [x] inputs_for (implemented as `<Inputs for={{...}} .../>`)
- [x] datetime_select (thanks to @miguel-s)
- [x] time_select (thanks to @miguel-s)
- [x] file_input (thanks to @miguel-s)
- [x] hidden_inputs_for (thanks to @miguel-s)
- [x] multiple_select (thanks to @miguel-s)
- [x] options_for_select (thanks to @miguel-s)

I'm not sure yet if it makes sense to create wrappers for all of them. Please let me know if you believe we should add/remove any helper to/from this list.

**Comment by zamith** [comment]
Is the idea to create built-in components like `<TextField>` or `<Form>` that then wrap the existing components or something lower level than that?

**Comment by msaraiva** [comment]
Hi @zamith!

So far, the only one we've found that would require a lower level implementation would be `inputs_for` as discussed [here](https://github.com/msaraiva/surface/issues/23#issuecomment-583168194). All the rest could, apparently, be just wrappers. 

Regarding `inputs_for`, in case we can't find a practical solution, we can still create a wrapper and use slot props to pass the form instance to the parent scope, instead of retrieving it from the context.

**Comment by zamith** [comment]
Makes sense. 👍 Is there any work on this yet? I'd maybe try to take a stab at it, but don't want to be doing duplicate work.

**Comment by msaraiva** [comment]
> Is there any work on this yet? 

Not that I'm aware of. I'll probably spend the next 2 weeks working on https://github.com/msaraiva/surface/issues/15. Only after that, I'll be able to work on anything else. 

> I'd maybe try to take a stab at it

That's awesome! 🎉 Feel free to drop any question, comment or snippet here in case you need any assistance. Just ask for feedback whenever you want :)

You can try building the most common components first, like `form`, `text_input`, etc. and then later move to other more complex ones like `inputs_for`. There's also a couple of examples that might help you to get started on the **"Contexts"** section in http://surface-demo.msaraiva.io/getting_started

Cheers.

**Comment by alexandrubagu** [comment]
Hi,

I've been using surface for a personal project and looks pretty awesome. If is possible I can give some help. I followed the docs, specially Context and I saw <TextInput> is wrapped inside a <Field>, if I understood correctly you did that in order to not duplicate the field name. If we want to make form components reusable I think we need to get label outside and then we don't need <Field>. Here's an example of form which don't need label:

```
<Form for={{ @changeset }} submit="search" class="form-inline" autocomplete="off">
  <TextInput name="search_input" class="p-2 mr-2" />
  <Submit name="Search" class="btn btn-md btn-primary" />
</Form>
```

Another problem which I see right now are tests. Do we need to add ecto as dependency only for test in order to create a changeset for a `Form` ?

Thanks,

**Comment by zamith** [comment]
I think that was only an example of how to use `contexts`, which is ultimately the goal of these built in components, so that each input can have the context of the form. It was not supposed to be a one size fits all implementation of field.

So, right now there is no reusable built in Form component, simply an example that you can or not follow. The example uses a changeset, but you can use [`form_for/4`](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html#form_for/4) with different arguments. You can even not use Phoenix helpers at all and write plain HTML, but that's besides the scope of Surface, I think.

**Comment by alexandrubagu** [comment]
@zamith, indeed there are couple of ways to work with `form_for/4`
```<%= form_for @changeset, Routes.user_path(@conn, :create), fn f -> %>```
```<%= form_for @conn, Routes.foo_path(@conn, :new), [as: :foo], fn f -> %>```
```<%= form_for :foo, Routes.foo_path(MyApp.Endpoint, :new), fn f -> %>```

I took a look over your starting branch and I saw `String.to_atom(@form)` which is not ok since atoms are limited. I'm interested in this, so we can work together if you want and we get some guidelines from @msaraiva

**Comment by zamith** [comment]
I thought about that, but what's the difference between:

`<%= form_for :foo, Routes.foo_path(MyApp.Endpoint, :new), fn f -> %>`

and

`<%= form_for String.to_atom(:foo), Routes.foo_path(MyApp.Endpoint, :new), fn f -> %>`?

The atom is not coming from user input, but from a developer. There is the off chance that you'll reach the limit of atoms, but it'll happen locally as well, I think. But, using an atom as possible name for the form was a choice of Phoenix.HTML, we're not adding anything on top of that.

That being said, for the text input, this is just a first version to have an idea of how it could look like. The final version should take some context from the form and probably use `@form` directly. 

However, I think that it's more important to get the dynamic props done before hand. Not being able to pass along properties we're not defining makes this not very usable.

**Comment by msaraiva** [comment]
Hi guys!

I dropped some comments at https://github.com/msaraiva/surface/pull/67#issuecomment-614690808.

**Comment by msaraiva** [comment]
> Another problem which I see right now are tests. Do we need to add ecto as dependency only for test in order to create a changeset for a Form ?

@alexandrubagu yeah, I think we'll probably have to add it as a dependency for the test environment. I don't see any other way. Any other suggestion is appreciated.

**Comment by izzues** [comment]
Hey, thank you so much for creating Surface, it looks amazing!

Are there any updates on the `inputs_for` component, or more specific ideas on how to implement it?

**Comment by msaraiva** [comment]
@izzues there was a limitation in `inputs_for` that didn't allow us to use it because it required an anonymous function to be passed. I just realized that there's a new `inputs_for` implementation that accepts passing the form instance like any other form input. See the new docs [here](https://github.com/phoenixframework/phoenix_html/blob/v2.14.2/lib/phoenix_html/form.ex#L382-L387).

I haven't tested yet but, in theory, we don't have to roll our own solution anymore. If you want to give it try, go ahead and let me know if you run into any issue.

@brainlid and @zamith as far as I can remember, you've tried to use `input_for` in the past but run into this problem, correct?

**Comment by msaraiva** [comment]
I started to implement a wrapper around `inputs_for` and realised that it would be great to have [this feature](https://github.com/msaraiva/surface/issues/66). This way each generated input could retrieve the related form data without using `:props` and `:let`.
