### ISSUE TITLE
Unable to call `send_update`

### ISSUE THREAD

**Issue by cadebward** [msaraiva/surface#40]
Hey @msaraiva! 

I've been noticing this same issue pop up lately. When we use the "modal pattern" of maintaining an open/close state in a stateful component, we're unable to called `send_update`.  (we're borrowing this idea from your docs)

For example, to open a modal you might call `Modal.open("id-here")`. That function will then call `send_update`:

```elixir
def open(id) do
  send_update(__MODULE__, id: id, open: true)
end
```

The problem is this line https://github.com/msaraiva/surface/blob/3d17ed8f3c21d2ea8e48d8b4208dbfc68405bcda/lib/surface/live_component.ex#L85 assumes that `__surface__` already exists, but it doesn't. It does exist on the component, but isn't added until we merge in the existing assigns with the new incoming assigns.

**Comment by cadebward** [comment]
To clarify, this isn't blocking. Since the target changes in live view, you can work around this easily by creating a `handle_event/3` in your modal component, and then targeting that component with a `phx-click` on your button. 

```elixir
def handle_event("open", _data, socket) do
  {:noreply, assign(socket, open: true)}
end
```

**Comment by msaraiva** [comment]
Hi @cadebward!

I was able to reproduce it. I'll push a fix for it soon.

Thanks for the report.

**Comment by msaraiva** [comment]
@cadebward!

Actually I can't reproduce it :)

I found another edge case which is when the content of the dialog is empty but that raise another error. What changes should I make in the `Dialog` demo to raise the same error?

Is the demo not working at all in your tests? Does it work if you use this branch? https://github.com/msaraiva/surface/tree/ms-context-api

**Comment by msaraiva** [comment]
Just to clarify, the PR is ready to go. As soon as I update the examples, I'll merge it.

In case you're using contexts, you need to adjust your code to the new API, i.e, you need to declare when using context.

Example for the Form component:

```elixir
  ...
  property change, :event

  context set form, :form

  def init_context(assigns) do
    opts = [phx_change: assigns.change.name, autocomplete: assigns.autocomplete]
    form = form_for(assigns.for, "#", opts)
    {:ok, form: form}
  end
...
```

Example for the Field component:

```elixir
  context set field, :atom, scope: :only_children
  context get form, from: Form

  def init_context(assigns) do
    {:ok, field: String.to_atom(assigns.field)}
  end
```

and finally, Textinput:

```elixir
```


> Note: `end_context/1` is no longer required.

**Comment by cadebward** [comment]
Hmm... I wonder if my problem was that I had a custom `update/2` function? I'll go ahead and close this since it was easy to work around and you aren't able to reproduce. Thanks for the update.

**Comment by miguel-s** [comment]
Hi @msaraiva @cadebward!

I'm running into the same issue with `send_update`. It seems to only occur when I use a custom `update/2` function, just as @cadebward suspected.

**Comment by msaraiva** [comment]
Hi @miguel-s!

Ideally, it shouldn't be necessary to pass it manually. The `:__surface__` assign belongs to the private API. I'll create a test for this case so we can work on a proper solution.

Cheers.

**Comment by miguel-s** [comment]
Hi @msaraiva!

Just want to confirm that https://github.com/msaraiva/surface/pull/114 fixed this issue for me.
I was still using the v0.1.0-alpha.2 release, but recently upgraded to the master branch.

Thanks!
