### ISSUE TITLE
Unable to use guard in `handle_event/3`

### ISSUE THREAD

**Issue by cadebward** [msaraiva/surface#41]
We are unable to pattern match in the function declaration and use the resulting assignments in a guard.

For example, this code:

```elixir
def handle_event(event, %{"id" => id}, socket) when id in ["foo"] do
  {:noreply, socket}
end
```

...raises the following compiler error:

```
== Compilation error in file lib/fe_web/live/editor.ex ==
** (CompileError) lib/fe_web/live/editor.ex:765: cannot find or invoke local id/0 inside guard. Only macros can be invoked in a guard and they must be defined before their invocation. Called as: id()
    (stdlib 3.11) lists.erl:1354: :lists.mapfoldl/3
    (elixir 1.10.1) expanding macro: Kernel.in/2
    (fe_web 0.1.0) lib/fe_web/live/editor.ex:765: FeWeb.Editor.__has_event_handler__?/1
    (surface 0.1.0) lib/editor.ex:1: Surface.EventValidator.__before_compile__/1
    (elixir 1.10.1) lib/kernel/parallel_compiler.ex:233: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

Guards still work if you are not pattern matching and assigning variables from inside of a map. For example, this still works:

```elixir
def handle_event(event, _data, socket) when event in ["foo"] do
  {:noreply, socket}
end
```

**Comment by msaraiva** [comment]
Hey @cadebward!

I took a look at this and my conclusion is that the static checking of events with guards is much more complicated than I initially thought. I'll just drop that static checking for now so we can move on until the first release. If we realize in the future that it's worth the trouble, we can try to add it back.
