### ISSUE TITLE
Components that render `@inner_content` generate a KeyError when no inner content is specified.

### ISSUE THREAD

**Issue by wrren** [msaraiva/surface#42]
If you define a component that renders inner content, e.g:

```elixir
defmodule Card do
  use Surface.Component

  def render(assigns) do
    ~H"""
    <div class="card>
      {{ @inner_content.() }}
    </div>
    """
  end
end
```

but then use it without defining any wrapped content, e.g:

```elixir
defmodule User do
  use Surface.Component

  def render(assigns) do
    ~H"""
    <Card />
    """
  end
end
```

The above will generate a KeyError in `content_handler/join_contents/3`, which assumes that an `:inner_content` assign exists.

**Comment by mazz-seven** [comment]
Shouldn't it throw an error?
I agree the error isn't informative, but I think it should throw one.

**Comment by wrren** [comment]
From what I've seen, it doesn't. Also I think it would be good if `@inner_content` was considered optional by default so that I can do things like this:

```elixir
defmodule Card.Header do
  use Surface.Component

  property title, :string, required: true

  def render(assigns) do
    ~H"""
    <div class="card-header">
        <p class="card-header-title">{{ @title }}</p>
        {{ @inner_content.() }}
   </div>
    """
  end
end
```

```elixir
defmodule User do
  use Surface.Component

  property user, :any, required: true

  def render(assigns) do
    ~H"""
    <Card>
      <Card.Header title={{ @user.display_name }} />
      {{ @user.bio }}
    </Card>
    """
  end
end
```

**Comment by mazz-seven** [comment]
I was thinking about it more and you're right. It will be better that way. Also, it will work better with Slots #3 as they should be optional also.
