### ISSUE TITLE
Allow loading surface components in .leex files

### ISSUE THREAD

**Issue by msaraiva** [msaraiva/surface#46]
### Suggestion

Add a `surface_component/3` function to enable loading components inside `*.leex` files

**Comment by mazz-seven** [comment]
Is this issue will resolve #35 also? 
If so I will close #35.

**Comment by msaraiva** [comment]
@mazz-seven I don't think so. You can leave it open for now.

**Comment by paultannenbaum** [comment]
I'll go ahead and pick this one up as first contribution if no one has started this

**Comment by msaraiva** [comment]
@paultannenbaum fantastic! Just to let you know, I haven't put a lot of thoughts on this one yet so I'm not even sure if it's possible to implement it without changes in phoenix itself. I have the feeling, it can't. So, in case you confirm that feeling, feel free to close this issue for now. We can come back to it in the future after we have the first stable release.

**Comment by paultannenbaum** [comment]
@msaraiva Just wanted to circle back that I did try implementing this, but didn't have too much luck. I think it is better to pause on this till #15 is completed, at which point this should be trivial to add in.

**Comment by msaraiva** [comment]
@paultannenbaum I agree. I'll close it for now.

**Comment by jessejanderson** [comment]
Now that it looks like #15 has been implemented, is this going to be readdressed? I sure would love to be able to use these components in my .leex templates. 😁

**Comment by msaraiva** [comment]
Hey @jessejanderson!

There's a proposal for this feature https://github.com/msaraiva/surface/issues/109. We should start working on it soon.
