### ISSUE TITLE
css_class transforms periods in class names into slashes

### ISSUE THREAD

**Issue by lnr0626** [msaraiva/surface#50]
```
<div class={{ "m-1.5": true }}>
</div>
```

Currently generates the following html:
```html
<div class="m-1/5">
</div>
```

However, I'd expect for it to generate the following html:
```html
<div class="m-1.5">
</div>
```

The cause is this function in surface.ex (line 301):
```elixir
  # TODO: Find a better way to do this
  defp to_kebab_case(value) do
    value
    |> to_string()
    |> Macro.underscore()
    |> String.replace("_", "-")
  end
```

Something like the following might give similar functionality without relying on `Macro.underscore()`:
```elixir
  defp to_kebab_case(value) do
    value
    |> to_string()
    |> String.replace(~r/([a-z])([A-Z0-9])/, "\\1-\\2")
    |> String.downcase()
  end
```

and should fix this specific issue; however I'm not sure if any code is relying on anything else that `Macro.underscore()` does as I'm not familiar with that.

For more context on why this is an issue for me, I'm using tailwind css which has class names that include periods.

**Comment by neilberkman** [comment]
This same code turns our our css class `clipboard__icon` into `clipboard--icon`. We follow [BEM naming conventions](https://en.bem.info/methodology/naming-convention/#naming-rules), which specify the use of underscores in class names.

**Comment by msaraiva** [comment]
Hi folks!

There are 2 issues here:

  1. We certainly can't use `Macro.underscore()`. Thanks @lnr0626 for finding that out!
  2. Is `camelCase` to `kebab-case` auto-conversion worth it?

I think `#1` can be fixed. However, `#2` concerns me more so I opened a separate issue (https://github.com/msaraiva/surface/issues/52) for discussion.
