### ISSUE TITLE
Question: is there an equivalent for <% end %>

### ISSUE THREAD

**Issue by lnr0626** [msaraiva/surface#53]
I've enjoyed working with surface so far; it has worked really well, and feels familiar coming from Vue/Angular/React type frameworks. Thank you for the work you've put into this!

One thing that feels a little odd is using the `live_redirect` and `live_patch` functions. It's fine when the link has a simple string as the contents (as that can just be passed as the first argument); however, when there's more complicated inner content I've been having to fall back to `<#Raw><% end %></#Raw>`. With standard leex it looks something like:
```
<%= live_redirect to: "something", class: "..." do %>
  <!-- inner contents -->
<% end %>
```
Which I'd expect to convert into something like:
```
{{ live_redirect to: "something", class: "..." do }}
  <!-- inner contents -->
{{ end }}
```
however, the compiler complains as `{{ end }}` gets translated into `<%= end %>`.

Is there a better way to handle that? Or is using `<#Raw><% end %></#Raw>` the way to go right now?

**Comment by msaraiva** [comment]
Hi @lnr0626!

My plan is to include wrapper components for `live_patch` and friends. For now, you could use your own wrapper. Something like:

```elixir
defmodule LivePatch do
  use Surface.Component

  alias Phoenix.LiveView.Helpers

  property label, :string
  property to, :string
  property class, :css_class

  def render(assigns) do
    if assigns.label do
      ~L"""
      <%= Helpers.live_patch(assigns.label, to: assigns.to, class: assigns.class) %>
      """
    else
      ~L"""
      <%= Helpers.live_patch to: assigns.to, class: assigns.class do %>
        <%= @inner_content.() %>
      <% end %>
      """
    end
  end
end
```

Then you can use it as:

```jsx
<LivePatch to={{ Routes.live_path(...) }}>
  Whatever markeup, component or text you like...
</LivePatch>
```

or 

```jsx
<LivePatch label="My link" to={{ Routes.live_path(...) }}/>
```
I created an [issue](https://github.com/msaraiva/surface/issues/54) for it.

**Comment by msaraiva** [comment]
As for other generic functions that depend on `do ... end`, we could create a macro component like:

```jsx
<#Apply fun={{ some_func }} args={{ ar1, arg2}}>
  <!-- inner contents -->
</#Apply>
```

But I'm not sure yet. I'm open to suggestions :)

**Comment by lnr0626** [comment]
That's pretty much what i ended up doing... I actually just wrote a wrapper around cond earlier today:
```
defmodule Cond do
  @moduledoc """
  A macro component which represents an equivalent of the cond statement.

  Example usage:
  <#Cond>
    condition1 ->
      <!-- inner contents -->
    condition2 ->
      <!-- inner contents -->
    ...
    true ->
      <!-- inner contents -->
  </#Cond>
  """
  use Surface.MacroComponent

  def translate({_node, _attrs, contents, _directives}, caller) do
    chunk_fun = fn
      el, [] -> {:cont, [el]}
      {:condition, _} = el, acc -> {:cont, Enum.reverse(acc), [el]}
      {:contents, _} = el, acc -> {:cont, [el | acc]}
    end

    after_fun = fn
      [] -> {:cont, []}
      acc -> {:cont, Enum.reverse(acc), []}
    end

    {["<%= cond do %>"],
     contents
     |> Enum.join("\n")
     |> String.trim()
     |> String.split("\n")
     |> Enum.map(fn line -> String.trim(line) end)
     |> Enum.with_index()
     |> Enum.map(&detect_line_type/1)
     |> Enum.chunk_while([], chunk_fun, after_fun)
     |> Enum.map(fn chunk -> process_chunk(chunk, caller) end), ["<% end %>"]}
  end

  defp detect_line_type({line, offset}) do
    if String.ends_with?(line, "->") do
      {:condition, {line, offset}}
    else
      {:contents, {line, offset}}
    end
  end

  defp process_chunk(chunk, caller) do
    {condition, offset} = Keyword.get(chunk, :condition)

    contents =
      chunk
      |> Keyword.get_values(:contents)
      |> Enum.map(fn {line, _} -> line end)
      |> Enum.join("\n")

    [
      ["<%", condition, "%>\n"],
      Surface.Translator.run(contents, caller.line + offset + 1, caller, caller.file),
      ["\n"]
    ]
  end
end
```

caveats apply to it (namely the conditions have to have be on their own line, and auto formatting doesn't 100% work), but it does work.

One thing I've run into is that you can't use components within live_patch and friends - i think it's because live_patch/etc. uses ~E under the hood, but haven't looked into it too far as I was able to work around it with another approach

**Comment by msaraiva** [comment]
Maybe the following would be easier to implement without any of the caveats because the parser would already give you all the pieces you need, i.e., the conditions (as directive :when) and the contents (as children):

```
<#Cond>
  <div :when={{ var == 1 }}>
    One
  </div>
  <div :when={{ var == 2 }}>
    Two
  </div>
  <div>
    Other value
  </div>
</#Cond>
``` 

In case the contents are simple text, you could use `<template>`:

```
<#Cond>
  <template :when={{ var == 1 }}>
    One
  </template>
  <template :when={{ var == 2 }}>
    Two
  </template>
  <template>
    Other value
  </template>
</#Cond>
```

**Comment by msaraiva** [comment]
We could even use the existing `:if` instead of `:when` but that might be confusing. I'm Not sure.

**Comment by lnr0626** [comment]
I like that idea - i think using a new directive would be better than reusing `:if`

`<template>` would also be useful if there were more than a single element without having to introduce extra wrappers. ie:
```
<#Cond>
  <template :when={{ var == 1 }}>
    One
  </template>
  <template :when={{ var == 2 }}>
      <div>el 1</div>
      <div>el 2</div>
  </template>
</#Cond>
```

**Comment by msaraiva** [comment]
> One thing I've run into is that you can't use components within live_patch and friends - i think it's because live_patch/etc. uses ~E under the hood

Interesting. I'm not sure why they don't use `~L`. We'll need to take a closer look at this issue before implementing #54.

**Comment by msaraiva** [comment]
I'm closing this one since Surface does not accept anything like `<% end %>` and probably never will. The approach is similar to React where every expression has to be complete/valid. Cases like the one reported here should be handled using wrapper components/functions as suggested.
