### ISSUE TITLE
Create wrapper components for live_patch and friends

### ISSUE THREAD

**Issue by msaraiva** [msaraiva/surface#54]

**Comment by lnr0626** [comment]
Continuing the thread about live_patch/redirect not supporting containers inside the do block:

I mentioned I thought it was because they were using `~E` under the hood instead of `~L`; however after looking at the code it's the method uses `Phoenix.HTML.Tag.content_tag`.
[Relevant block](https://github.com/phoenixframework/phoenix_live_view/blob/792ee745b9fde7df92734e16fb08f3ebee65fae0/lib/phoenix_live_view/helpers.ex#L96-L109) show below:
```elixir
  defp live_link(type, block_or_text, opts) do
    uri = Keyword.fetch!(opts, :to)
    replace = Keyword.get(opts, :replace, false)
    kind = if replace, do: "replace", else: "push"

    data = [phx_link: type, phx_link_state: kind]

    opts =
      opts
      |> Keyword.update(:data, data, &Keyword.merge(&1, data))
      |> Keyword.put(:href, uri)

    Phoenix.HTML.Tag.content_tag(:a, opts, do: block_or_text)
  end
```

**Comment by msaraiva** [comment]
So I suppose it will only work when the content is simple markup even if you are not using Surface. I mean, if you try to use just LV and use `<%= live_component SomeComponent, ... %>` as the content, it won't work. Right?

If that's the case, this is also a LiveView issue and we have two options:

1. Open an issue on the phoenix LV project to check why it doesn't accept it. It might be by design or due to some technical limitation. In either case, it would be nice to know if they intend to change this behaviour in the near future or not. I think since the component API is quite new and usually the content of those helpers a simple, users may have not faced this problem yet.

1. Implement our own helpers without depending on `content_tag`.

I think choosing `#2` will depend on the answer of `#1`.

**Comment by lnr0626** [comment]
Yeah, `live_component` within `live_patch`/`live_redirect` fails with the same error message. I'll go ahead and post an issue over there.

I already have a live patch/live redirect component that doesn't use `content_tag` which I'd be happy to push up as a PR; though I understand if you want to hold off until we get feedback from the LV project

**Comment by msaraiva** [comment]
> I already have a live patch/live redirect component that doesn't use `content_tag` which I'd be happy to push up as a PR

Awesome! Feel free to submit a PR. We can replace the implementation later in case they update the original one.
