### ISSUE TITLE
Allow passing context assigns to slot content

### ISSUE THREAD

**Issue by mathewdgardner** [msaraiva/surface#66]
### Current behavior

The child does not fetch the context if rendered separately from the context provider:

```elixir
defmodule Parent do
  use Surface.Component

  slot default

  def render(assigns) do
    ~H"""
    <div>
      <Parent.ContextProvider foo="bar">
        <slot />
      </Parent.ContextProvider>
    </div>
    """
  end
end

defmodule Parent.ContextProvider do
  use Surface.Component

  property foo, :string
  context set foo, :string, scope: :only_children
  slot default

  # The foo prop is passed here and so we can use it
  def init_context(assigns) do
    {:ok, foo: assigns.foo}
  end

  def render(assigns) do
    ~H"""
    <slot />
    """
  end
end

defmodule Child do
  use Surface.Component

  context get foo, from: Parent.ContextProvider

  def render(assigns) do
     # @foo is nil here
    ~H"""
    <div>{{ @foo  }}</div>
    """
  end
end

defmodule ExampleWeb.ContextLive do
  use Surface.LiveView

  def render(assigns) do
    ~H"""
      <Parent>
        <Child/>
      </Parent>
    """
  end
end
```

If we render it all at once in either the live view or a component, the context works as expected. It's only once they are broken apart this issue arises.

### Expected behavior

Child components can consume context from a parent rendered elsewhere.

**Comment by msaraiva** [comment]
Hi @mathewdgardner!

`<slot/>` is translated to the anonymous function `@inner_content.()` and as such, can only access variables (consequently the context) that belong to the same scope where it was defined. So you need to either move `Parent.ContextProvider` out of `Parent` and place it explicitly as a parent of `Child` or pass whatever you need using `<slot :props={{ some_prop: value }}/>` and then retrieve it using `:let={{ some_prop: var }}`.

I'm currently working on the documentation of the slots API, where I explain how `:props` and `:let` works. I should release the new docs by the end of the week. In the meantime, in case you need to see how it works, you can take a look at [slot_test.exs](https://github.com/msaraiva/surface/blob/9997a11a64feea44075ab63e6ba79428d33b3d79/test/slot_test.exs). There are many tests using `:props` and `:let`.
