### ISSUE TITLE
UI Components (WIP)

### ISSUE THREAD

**Issue by guidotripaldi** [msaraiva/surface#83]
First thank you for this library, I really like the abstraction and its elegance! Reading the documentation I noticed the (currently empty) **UI Components** entry, can you anticipate us some informations on what it will implement? It will be a separate library with a collection of independent components? It will be a sort of UI framework?
If you are already ready to give some details and guidelines, the community that is being formed around Surface could start to working on it (and I'd like to contribute, for what I can), instead of developing, each one independently, similar components.

**Comment by msaraiva** [comment]
Hi @guidotripaldi!

> can you anticipate us some informations on what it will implement? It will be a separate library with a collection of independent components? It will be a sort of UI framework?

The plan is to have a separate project for each different CSS solution, e.g. `surface_bulma`, `surface_tailwind`, `surface_bootstrap` and so on. I have already a few components for Bulma that I needed to create Surface's website. As soon as I add some minimal documentation, I'll make them available along with some examples in the `UI Components` section.

> If you already ready to give some details and guidelines, the the community that is being formed around Surface could start to working on it (and I'd like to contribute, for what I can), instead of developing, each one independently, similar components.

That's fantastic! 🎉 I'll create the `surface_bulma` project this week and add a couple of components to it so they can serve as a starting point. The API of those components will be very similar to [Buefy](buefy.org)'s components. In case you're not using `Bulma`, don't worry, you'll be able to easily adapt them to any other CSS lib of your choice.

**Comment by machineloop** [comment]
Thanks for your work on this library @guidotripaldi  , coming from React, this feels like a more natural way to write BE components! I'd be willing to pitch in on the Bulma or another variation of components, looking forward to checking out `surface_bulma`.

Sidenote: is there a way to contribute to the docs website with a PR, I've caught a typo or two and looked for a way to fix, but didn't see a repo open for PRs...

**Comment by msaraiva** [comment]
Hi @machineloop!

> I'd be willing to pitch in on the Bulma or another variation of components

That's great to hear! ❤️

>  is there a way to contribute to the docs website with a PR, I've caught a typo or two and looked for a way to fix, but didn't see a repo open for PRs...

Not yet. I have to move all components to public repos too before opening it. In the meantime, if you find any typo or have any suggestion for the docs, feel free to open an issue here and drop your comments. I'll be glad to update it.

**Comment by joshuataylor** [comment]
Fantastic to hear, as I'm currently developing with bootstrap, and I guess others will too, I'll be happy to contribute back bootstrap related features.

**Comment by neilberkman** [comment]
Hi @msaraiva, just wondering if `surface_bulma` might be public soon? I'd like to do something similar for Tailwind and having a Bulma implementation as a starting point would be tremendous/y helpful. Thanks!

**Comment by msaraiva** [comment]
Hi @neilberkman!

The first 3 components of `surface_bulma` are available at [github.com/msaraiva/surface_bulma](https://github.com/msaraiva/surface_bulma).

Documentation and live examples have also been updated. The components are:

  * [Button](http://surface-demo.msaraiva.io/uicomponents/Button)
  * [Table](http://surface-demo.msaraiva.io/uicomponents/Table)
  * [Tabs](http://surface-demo.msaraiva.io/uicomponents/Tabs)

The components listed above along with the new built-in form components also available in version `alpha.2` use most of the concepts required to build any component, including slots, events, context and so on.

Feel free to contact me in case you need any assistance.

**Comment by neilberkman** [comment]
@msaraiva thanks so much, this is incredibly helpful!

**Comment by tschmidleithner** [comment]
Hi,

first of all, I want to thank the contributors and especially @msaraiva for the amazing work on the Surface library. Having worked with Phoenix Framework, Phoenix LiveView and React in recent years, a library such as Surface is really helpful for developing web applications in 2020 :+1: . 

Heavily inspired by the work of [Surface Bulma](https://github.com/msaraiva/surface_bulma), I started with the implementation of a [Bootstrap (v4) library](https://getbootstrap.com) for Surface. The library can be found in the [surface_bootstrap4](https://github.com/tschmidleithner/surface_bootstrap4) repository. Furthermore, a simple Phoenix LiveView demo application using the surface_bootstrap4 library can be found [here](https://github.com/tschmidleithner/surface_bootstrap4_demo). A screenshot of the preview is also provided in the demo repo.

Currently, only support for buttons is provided but I am planning to roll out new components such as Alerts, Navs, Cards, etc. soon. Additionally, tests are implemented as parameterized tests. The library is of course work in progress and contribution and feedback is more than welcome!  :blush:

**Comment by msaraiva** [comment]
Hey @tschmidleithner!

Nice work! Looking forward to seeing the full suite. Let me know if you run into any issue or have any question.

In case you want the formatter to follow Surface's default formatting settings, e.g. no parenthesis for API functions, you need to configure it accordingly. In your `.formatter`, add `:surface` to `import_deps`:

```elixir
[
  import_deps: [:surface],
  ...
]
```

**Comment by tschmidleithner** [comment]
Hi @msaraiva,

thanks for the feedback, I just added the configuration for the surface formatter.

Additionally, I have the following question: I often have the use-case that I want to add custom CSS classes to my components which is especially the case when I want to use padding or margin. What do you think is the best way to directly support additional CSS classes for components while preserving the default CSS classes applied to a component? 

E.g. when I have a button component and I want to add margin to it. Intuitively, I would expect that

```jsx
<Button class="m-7" color="primary">Button with margin 7 defined in custom CSS</Button>
```

renders to

```jsx
<button type="button" class="btn btn-primary m-7">...</button>
```

For this, I could simply add a property `class` of type `:string` to the button component and add the property to the keyword list `class={{ ... }}` in the `render/1` callback of the button. However, I am not sure if this is the cleanest way to enable this functionality. What do you think? Is this a valid approach?

**Comment by msaraiva** [comment]
@tschmidleithner I think it's certainly a valid approach, however, I would type the `class` property as `:css_class` instead of `:string`. This way the user can still benefit from the syntactic sugar provided by Surface. Then you can just pass it along with any other item:

```
class={{ :btn, @class, "btn-#{@color}": @color, ... }}
```

You might see an extra white space when `class` is not provided but it will do no harm. I'll make sure I'll trim the values later.

**Comment by tschmidleithner** [comment]
@msaraiva Great, this feature is implemented, thanks!

**Comment by msaraiva** [comment]
Since working on UI components will be a continuous work, I'm closing this in favor of #92.

**Comment by gitmarcdv** [comment]
At this point I cannot (yet) contribute, but I want to encourage all of you and in particular msaraiva with the great work done here.
As soon as I see a possibility to free up time, I'll be glad to help (drawning in work atm, sorry for that).
