### ISSUE TITLE
`ArgumentError` in `Surface.API.generate_docs` when compiling a component with `@moduledoc false`

### ISSUE THREAD

**Issue by Blond11516** [msaraiva/surface#85]
When building a project that contains any Surface component (i.e. any module using Component, LiveView, LiveComponent or MacroComponent) with `@moduledoc false`, compilation fails with the following error:
![image](https://user-images.githubusercontent.com/44734484/82610142-dab0ca00-9b8b-11ea-9e15-d5a356057ac6.png)

## Expected Behavior
The project should compile successfully.

## Current Behavior
Compilation fails.

## Possible Solution
Adding the following arm to the `case` statement of Surface.API.generate_docs/1 appears to fix the issue:
```elixir
{_line, false} ->
  {env.line, props.doc}
```
This solution returns the same doc as if the `@moduledoc`attribute was not specified at all.

## Steps to Reproduce
1. Create a mix project
2. Add Surface as a dependency
3. Create a module with `using Surface.Component` and `@moduledoc false`
4. Run `mix compile`

## Context (Environment)
Elixir version: 1.10.3-otp-22
Surface version: Latest from master

If this an actual issue and the proposed solution is acceptable I would be happy to submit a PR to fix this!

**Comment by msaraiva** [comment]
Fixed in https://github.com/msaraiva/surface/commit/b18a1ad8597a8647e30762404c6792f0250291ca.

Thanks for reporting this issue!
