### ISSUE TITLE
Custom template engines

### ISSUE THREAD

**Issue by izzues** [msaraiva/surface#88]
Hello,

Is it currently possible to create Surface components using languages such as Temple or Slime? If not, what kind of work would it take?

Thank you!

**Comment by msaraiva** [comment]
Hi @izzues!

> Is it currently possible to create Surface components using languages such as Temple or Slime?

Unfortunately not.

> If not, what kind of work would it take?

I believe It would take a lot of work, however, it might be feasible after #15 since we will have a language-agnostic tree that could be generated by any parser.
