### ISSUE TITLE
Un-terminated markup codes like <hr> cause issues

### ISSUE THREAD

**Issue by brainlid** [msaraiva/surface#9]
This markup was copied from an EEx template into a `~H` one.

![image](https://user-images.githubusercontent.com/808984/70832167-a43b7b80-1db1-11ea-8085-bd05566ccbbb.png)

The problem is the `<hr>`. The compiler error is:

```
** (Surface.Translator.Parser.ParseError) /my_app/views/editor/placeholder.ex:14: expected end of string
    (surface) lib/surface/translator/parser.ex:222: Surface.Translator.Parser.parse/3
    (surface) lib/surface/translator.ex:23: Surface.Translator.run/4
    (surface) expanding macro: Surface.sigil_H/2
    (fe_web) lib/fe_web/views/editor/placeholder.ex:13: FeWeb.Editor.Placeholder.render/1
    (elixir) lib/kernel/parallel_compiler.ex:229: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```
After trial and error I realized it was the `<hr>`. When I changed it to `<hr />` then it worked fine.

The solution is either support markup like the non-xml valid `<hr>` or improve the error message to help identify what the problem is.

**Comment by msaraiva** [comment]
Improving the error message is the way to go. There's a new parser that still has to be merged that address this by giving the following message:

```
.../placeholder.ex:18: expected closing tag for "<hr>"
```

**Comment by brainlid** [comment]
Perfect!

**Comment by msaraiva** [comment]
@brainlid the new parser on master accepts HTML void elements like `<br>` or `<hr>`. No need to self-close them anymore. You can copy and paste them freely now ;)

**Comment by msaraiva** [comment]
@brainlid BTW, with the new parser you'll have to make a small change in you `<Form>` component. Please use:

```
<#Raw></form></#Raw>
```
instead of:

```
{{ raw("</form>") }}
```
