### ISSUE TITLE
Compatibility with client-side JS

### ISSUE THREAD

**Issue by izzues** [msaraiva/surface#93]
I've been using `phx-update="ignore"` in a LiveComponent so I can use an element that should be entirely handled by client-side JS. The script just replaces the textarea with a WYSIWYG editor. It's something like this:

```
<div phx-update="ignore">
    <link rel="stylesheet" href="editor.css">
    <textarea id="editor"></textarea>
    <script src="editor.js"></script>
</div>
```

When I try the same thing with Surface, the element just goes blank.

Is there any way to get this working?

(To be honest I'm not sure I should be putting the `script` and `link` tags inside the ignored node... Any suggestions are welcome!)

Thanks in advance!

**Comment by msaraiva** [comment]
Hey, @izzues!

It's hard to tell what's going on by just seeing the snippet above. Can you provide a sample project reproducing the issue? If there's no syntax error, it should work the same way as in LiveView. Also, you may need to add an id to the `div` with the `phx-update`. I believe LV requires it.

> To be honest I'm not sure I should be putting the `script` and `link` tags inside the ignored node...

I believe they should probably go in the `<head>` section.

**Comment by izzues** [comment]
Sorry for taking your time, you're right, all I had to do was add an ID to the element. Thank you so much!
